### ISSUE TITLE
[FEATURE] Raytrace Bypass for Crystal Aura

### ISSUE THREAD

**Issue by unfidelity** [3arthqu4ke/3arthh4ck#10]
looking away or inverting where you are looking away from the player that you are attacking so your rotations flip lets you bypass ncp blockvisible check for a few placements. In this video im using antiaim in future to look away for me automatically when crystal aura is off.

https://streamable.com/pzutp3

this works on constantiam and raytraceanarchy

**Comment by 3arthqu4ke** [comment]
Would a rotation flip option in AntiAim be enough? And then you just toggle AutoCrystal on and off?

**Comment by Ruupin** [comment]
Congratulations for finding this after its been public for almost 2 years

**Comment by HausemasterIssue** [comment]
Ruupin more like Poopin' hahaha

**Comment by unfidelity** [comment]
> Would a rotation flip option in AntiAim be enough? And then you just toggle AutoCrystal on and off?

yes that would be an ok solution to it

**Comment by 3arthqu4ke** [comment]
I will leave this open for now. I'll maybe (probably not) revisit this for a more automated solution.

**Comment by Bjottt** [comment]
no yaw only yes pitch

**Comment by GurteX** [comment]
> I will leave this open for now. I'll maybe (probably not) revisit this for a more automated solution.

~~automated solution~~ robotic solution

**Comment by 3arthqu4ke** [comment]
Finally got around to do it, thats const: https://streamable.com/yhn4rs
