### ISSUE TITLE
[FEATURE] Add CEVbreaker and rewrite piston aura

### ISSUE THREAD

**Issue by GRIFFiin** [3arthqu4ke/3arthh4ck#102]
The Piston Aura in this client is somehow broken and the one from gs++ is sometimes broken.

Would be cool to have CevBreaker with a lot of options to permit fast camper kill.

thanks for updating 3arthh4ck !

**Comment by GurteX** [comment]
> The Piston Aura in this client is somehow broken and the one from gs++ is sometimes broken.
> 
> Would be cool to have CevBreaker with a lot of options to permit fast camper kill.
> 
> thanks for updating 3qrthh4ck !

1. Config issue
2. Brain issue
3. 3arthh4ck*

**Comment by crystalpvpnn** [comment]
retard

**Comment by GurteX** [comment]
retard

**Comment by Zane2b2t** [comment]
retard

**Comment by Random3131** [comment]
I hope your stub your toe
