### ISSUE TITLE
[FEATURE] HUD editor

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#104]
**Is your feature request related to a problem? Please describe.**
Make the HUD editor a working module

**Describe alternatives you've considered**
Just hide the module untill it will recive more developement, or add in the description of the module "(Needs Rewrite)"

**Additional context**
It would be a great module

**Comment by mdo992** [comment]
NOOOO

**Comment by mdo992** [comment]
@Ai2473 please keep this open

**Comment by mdo992** [comment]
REOPEN THIS ISSUE

**Comment by mdo992** [comment]
REOPEN!!!!!!!!
