### ISSUE TITLE
[BUG] Popchams animation

### ISSUE THREAD

**Issue by xyzbtw** [3arthqu4ke/3arthh4ck#107]
**Describe the bug**  
Animations nearly always have their legs spread wide open like in the ss, even while the player is standing in 1 place
**To Reproduce**  
Turn on popchams and the copy animations thing,
pop a player/fakeplayer

**Expected behavior**  
A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in.
Not as wide leg animations like in future
**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you!

**Additional context**  

**Checklist**
![unknown](https://user-images.githubusercontent.com/89705569/185707424-685bf80f-3044-4296-b9df-4b26b5beddbb.png)

- [x] I know how to properly use check boxes.
- [ ] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [ ] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
@cattyngmd fix whenever you want, not really urgent since its better than the old one anyways

**Comment by cattyngmd** [comment]
> @cattyngmd fix whenever you want, not really urgent since its better than the old one anyways

oh yeah ill fix that

**Comment by threevt** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Animations nearly always have their legs spread wide open like in the ss, even while the player is standing in 1 place **To Reproduce** Steps to reproduce the behavior: Turn on popchams and the copy animations thing, pop a player/fakeplayer
> 
> **Expected behavior** A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in. Not as wide leg animations like in future **Crashlog** If you crashed and you don't provide a crashlog I will ignore you!
> 
> **Additional context** Add any other context about the problem here.
> 
> **Checklist** ![unknown](https://user-images.githubusercontent.com/89705569/185707424-685bf80f-3044-4296-b9df-4b26b5beddbb.png)
> 
>     * [x]  I know how to properly use check boxes.
> 
>     * [ ]  I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
> 
>     * [ ]  I followed the issue template.

when you take crystal or any type of damage damage your legs and arms move but the fake player does not show that

**Comment by sexshop1337** [comment]
пошел нахуй
