### ISSUE TITLE
pingbypass ca issue

### ISSUE THREAD

**Issue by jaydonjrl** [3arthqu4ke/3arthh4ck#109]
when i go on mainhand servers with pingbypass  it wont  automatically swap  to my end crystals when using ca

**Comment by threevt** [comment]
Do you have Autoswitch on in the ca?

**Comment by Zane2b2t** [comment]
> when i go on mainhand servers with pingbypass it wont automatically swap to my end crystals when using ca

Just turn on autoswitch for ac in pb-gui

**Comment by jaydonjrl** [comment]
> 

i do have autowswitch on in ca its just wont switch

**Comment by jaydonjrl** [comment]
> 

there are two settings for autocrystal in pb gui

**Comment by Zane2b2t** [comment]
> > 
> 
> there are two settings for autocrystal in pb gui

Config issue
