### ISSUE TITLE
[FEATURE] Shrink And scale animation for HoleESP

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#117]
Like the fade animation, add an option so the hole esp grows when getting close to it, and shrink when u get far away from it, ive seen it in Fire 0.1 which is private so it shouldnt be hard!!!

**Comment by GurteX** [comment]
that looks bad

**Comment by xyzbtw** [comment]
Also add an animated triangular hole esp like in moloch.su like in this video https://www.youtube.com/watch?v=4OnaCSXgrmw&t=12s

**Comment by cattyngmd** [comment]
> Also add an animated triangular hole esp like in moloch.su like in this video https://www.youtube.com/watch?v=4OnaCSXgrmw&t=12s

maybe as plugin

**Comment by xyzbtw** [comment]
Mayve

> > Also add an animated triangular hole esp like in moloch.su like in this video https://www.youtube.com/watch?v=4OnaCSXgrmw&t=12s
> 
> maybe as plugin

I guess it would be cool as a plugin aswell, sadly I don't know how to code lmao

**Comment by Zane2b2t** [comment]
> Also add an animated triangular hole esp like in moloch.su like in this video https://www.youtube.com/watch?v=4OnaCSXgrmw&t=12s

Shrink and grow animation too
