### ISSUE TITLE
chams

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#124]
there's a bug when you turn on chams with image mode, it won't render player and just show the item whose are being hold

**Comment by GurteX** [comment]
![Screenshot_20220822-132304_YouTube.png](https://user-images.githubusercontent.com/46028187/185957802-458eeba5-0fe1-4925-86f8-ff52f8e0add6.png)

**Comment by Zane2b2t** [comment]
> there's a bug when you turn on chams with image mode, it won't render player and just show the item whose are being hold

there's also a bug where if u turn on normal chams items ppl hold are invisible idk (not using image)
