### ISSUE TITLE
[BUG] Placement/Extrapolate Error part 2

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#133]
https://streamable.com/p5lv34 I don't have extrapolate on, the ca placement tries to predict the movement??? but it still cant predict if we are behind enemy (same applies if we are using extrapolate) 
also it weirdly multiplaces on stairs (started happening after you made changes to extrapolate) https://streamable.com/1gs78v 
still not using extrapolate in the second clip

**Comment by cattyngmd** [comment]
> https://streamable.com/p5lv34 I don't have extrapolate on, the ca placement tries to predict the movement??? but it still cant predict if we are behind enemy (same applies if we are using extrapolate)

Its not trying to predict the player's movement. AutoCrystal places crystals on the closest and most damaging position, so its not really a bug.

**Comment by Random3131** [comment]
> > https://streamable.com/p5lv34 I don't have extrapolate on, the ca placement tries to predict the movement??? but it still cant predict if we are behind enemy (same applies if we are using extrapolate)
> 
> Its not trying to predict the player's movement. AutoCrystal places crystals on the closest and most damaging position, so its not really a bug.

its still the same case while using extrapolate

**Comment by cattyngmd** [comment]
> > > https://streamable.com/p5lv34 I don't have extrapolate on, the ca placement tries to predict the movement??? but it still cant predict if we are behind enemy (same applies if we are using extrapolate)
> > 
> > 
> > Its not trying to predict the player's movement. AutoCrystal places crystals on the closest and most damaging position, so its not really a bug.
> 
> its still the same case while using extrapolate

oh ok i didnt notice that

**Comment by Random3131** [comment]
https://streamable.com/0r6cyg using extrapolate

**Comment by 3arthqu4ke** [comment]
Do you have Pre-Calc on? If not send your AutoCrystal config. If yes, thats probably it. Pre-Calc checks the positions around their feet first, I have not taken Extrapolation into account for that yet...

**Comment by Random3131** [comment]
where is pre calc located?

**Comment by Random3131** [comment]
nvm found it

**Comment by Random3131** [comment]
https://streamable.com/ysdzek turned off pre calc still same 

 "AutoCrystal": {
    "Danger-Health": "0.0",
    "Water": "false",
    "Shield": "false",
    "Render": "true",
    "MineBypass": "None",
    "PushOutOfBlocks": "MP",
    "FallBack": "true",
    "Async-Calc": "true",
    "Force-AntiTotem": "false",
    "Obby-Fallback": "true",
    "LiquidRotate": "None",
    "BlockExtraMode": "Optimistic",
    "Sequential": "false",
    "Obby-Rotate": "None",
    "PlaceSwing": "Post",
    "FocusExponent": "0.0",
    "BypassTicks": "10",
    "Instant": "true",
    "AntiFriendPop": "Place",
    "MinDamage": "5.08",
    "ExplosionThread": "true",
    "EndSequenceOnSpawn": "false",
    "TotemSync": "true",
    "NegativeBreakTrace": "true",
    "ShieldSelfDamage": "2.0",
    "Smart-Post": "true",
    "NCP-Range": "false",
    "God-AntiTotem": "false",
    "BreakTrace": "4.02",
    "Danger-FacePlace": "false",
    "Pseudo-Dead": "true",
    "SlowPlaceDelay": "0",
    "MotionThread": "true",
    "SetDead": "true",
    "Suicide": "false",
    "PlaceCooldown": "0",
    "SwitchBack": "false",
    "Force-Place": "100",
    "TerrainCalc": "true",
    "Switch-Message": "true",
    "ManualDelay": "0",
    "ObbyCalc": "500",
    "LateBreakThread": "true",
    "BreakRange": "5.1",
    "P-Extra-Weight": "1.25",
    "TargetRange": "12.0",
    "RotationThread": "Predict",
    "Enabled": "true",
    "MaxCancel": "10",
    "InterruptSpeedmine": "false",
    "ShieldMinDamage": "6.0",
    "MultiThread": "true",
    "MultiPlace-Calc": "false",
    "TickThreshold": "6",
    "Pre-CalcDamage": "15.0",
    "Place": "true",
    "CooldownBypass": "None",
    "BreakSwing": "Post",
    "ShieldCount": "1",
    "Page": "MultiThread",
    "Fade-Time": "50",
    "Name": "AutoCrystal",
    "Partial": "1.0",
    "NoPacketFlyRotationChecks": "true",
    "CoolDown": "0",
    "Old-PingBypass": "false",
    "RB-Yaw": "180.0",
    "PickaxeOnly": "false",
    "SurroundSync": "true",
    "FocusDiff": "0.0",
    "Tool-Check": "true",
    "PlaceRange": "5.04",
    "AsyncServerThread": "true",
    "LiquidDelay": "500",
    "DebugAntiPlaceFail": "false",
    "Obsidian": "true",
    "Pre-Calc": "None",
    "IgnoreNonFull": "true",
    "Instant-Dead": "true",
    "Sponges": "false",
    "Obby-MinDamage": "7.0",
    "BlockChangeThread": "true",
    "UseAsOffHandBind": "false",
    "SlowBreak": "0.1",
    "LiquidObby": "true",
    "Efficient": "true",
    "PreSpawn": "3",
    "FallBackDmg": "3.0",
    "MainHand": "false",
    "Fade": "true",
    "MaxSelfBreak": "8.6",
    "AntiWeakness": "Switch",
    "MaxEarlyThread": "10",
    "Danger-Speed": "false",
    "PlaceTrace": "4.08",
    "ID-Packets": "2",
    "Inside": "false",
    "Pre-SyncCheck": "false",
    "SetAir": "true",
    "DamageMode": "Indicator",
    "ForceBypass": "false",
    "Toggle": "Normal",
    "End-Rotations": "250",
    "Instant-Offhand": "true",
    "SyncDelay": "500",
    "AvgBreakExtra": "true",
    "SoundThread": "true",
    "TraceWidth": "-1.0",
    "Simulate-Place": "0",
    "BreakDelay": "0",
    "Danger-Force": "false",
    "RayBypassFacePlace": "true",
    "IndicatorColor": "FFBE0505-false-false-false-100.0-100.0-100.0",
    "ObsidianBypass": "None",
    "ShrinkPush": "true",
    "AntiPlaceFail": "false",
    "PickAxe-Hold": "false",
    "HelpingBlocks": "1",
    "Fallback-Difference": "10.0",
    "SimulateExplosion": "false",
    "Break": "true",
    "AntiWeaknessBypass": "None",
    "B-Norm-Weight": "1.25",
    "Y-Calc": "false",
    "1.13-Entities": "false",
    "Shield-PrioritizeHealth": "false",
    "Holding-Check": "true",
    "P-Norm-Weight": "1.25",
    "MinBreakDmg": "0.0",
    "MultiPlace": "1",
    "Hidden": "Visible",
    "Min-FP": "2.0",
    "BlockDestroyThread": "true",
    "Obby-Terrain": "true",
    "Block-Extrapolation": "20",
    "MultiPlace-MinDmg": "true",
    "Negative-Ticks": "6",
    "Lava": "false",
    "ID-Delay": "15",
    "AntiTotem": "true",
    "Fallback-Trace": "true",
    "DamageRender": "None",
    "Max-Difference": "1",
    "Motion-Calc": "false",
    "AvgPlaceExtra": "true",
    "Realtime": "true",
    "God-Swing": "Always",
    "Render-Time": "250",
    "Force-Break": "100",
    "Fast-Obby": "0",
    "EndSequenceOnExplosion": "true",
    "RayBypassFallback": "true",
    "SlowBreakDelay": "0",
    "SmartRange-Ticks": "6",
    "Rotate": "None",
    "OverrideBreak": "true",
    "AW-Instant": "true",
    "Rotations-Existed": "0",
    "FocusRotationCompare": "true",
    "AntiNaked": "false",
    "Min-Offset": "0.5",
    "SpawnThread": "true",
    "Target": "Damage",
    "SelfExtrapolation": "true",
    "Attempts": "500",
    "MaxSelfPlace": "9.8",
    "Focus-Rotations": "false",
    "Existed": "0",
    "Outline": "BDB2E7F6-false-false-false-200.0-100.0-100.0",
    "Rotate-Mode": "Normal",
    "MinRotationDiff": "0.0",
    "Remove-Time": "1000",
    "ShieldRange": "10.0",
    "EntityThread": "true",
    "Obby-Raytrace": "Fast",
    "Client-Blocks": "false",
    "SmartRange": "All",
    "Discrete-Sync": "false",
    "Totem-Health": "1.5",
    "Pop-Damage": "12.0",
    "Death-Time": "0",
    "ThreadDelay": "20",
    "EndSequenceOnBreak": "false",
    "Always-Calc": "false",
    "OverridePlace": "true",
    "Break-Angle": "180.0",
    "FacePlace": "7.92",
    "Max-DamageDiff": "0.0",
    "Interact": "false",
    "Smart-Trace": "false",
    "RayBypassRotationTime": "500",
    "Place-Angle": "180.0",
    "Danger-Sync": "false",
    "RayTraceBypass": "true",
    "HoldFacePlace": "true",
    "IgnoreLavaItems": "false",
    "RB-Pitch": "90.0",
    "DestroyThread": "true",
    "BreakHand": "MainHand",
    "Break-Extrapolation": "20",
    "Priority": "1500",
    "PlaceDelay": "0",
    "Box": "22A9E8F9-false-false-false-200.0-100.0-100.0",
    "Range": "12.0",
    "Obby-Swing": "Once",
    "Extrapolation": "20",
    "Ping-Existed": "false",
    "RenderExtrapolation": "false",
    "Obby-PreSelf": "true",
    "Break-Confirm": "250",
    "Manually": "false",
    "LiquidRayTrace": "true",
    "ObbyHand": "MainHand",
    "Draw-Box": "true",
    "Wait": "2",
    "MultiTask": "true",
    "DoubleExtraCheck": "false",
    "ClearPost": "true",
    "1.13+": "false",
    "Gameloop": "true",
    "ObbyDelay": "500",
    "Spectator": "false",
    "Absorb": "false",
    "PlaceHand": "MainHand",
    "AutoSwitch": "Always",
    "Place-Confirm": "250",
    "SlowPlace": "0.1",
    "DamageSync": "false",
    "B-Extra-Weight": "1.25",
    "ID-Offset": "1",
    "CombinedTrace": "3.78",
    "FeetBuffer": "5",
    "SmartBreakTrace": "true",
    "Packets": "1",
    "Height": "0.05",
    "Place-Height": "1.0",
    "ArmorPlace": "26.0",
    "Obby-Switch": "false",
    "AntiFeetPlace": "false",
    "Force-Slow": "false",
    "Attack": "Always",
    "ID-Predict": "false",
    "EarlyFeetThread": "true",
    "Sync-Force": "true",
    "Smooth-Speed": "0.59",
    "RotationExponent": "0.0",
    "ShieldPlaceDelay": "50",
    "SoundRemove": "true",
    "ObbySafety": "true",
    "RequireOnGround": "true",
    "Seq-Time": "0",
    "ServerThread": "true",
    "Max-Offset": "2.0"
  },

**Comment by 3arthqu4ke** [comment]
Could you turn on RenderExtrapolation and make a video?

**Comment by 3arthqu4ke** [comment]
It could also be that the FakePlayer does not get Extrapolated, let me check.

**Comment by Random3131** [comment]
> It could also be that the FakePlayer does not get Extrapolated, let me check.

other client's extrapolation works fine

**Comment by Random3131** [comment]
https://streamable.com/auyjds

**Comment by 3arthqu4ke** [comment]
So basically it never really worked to begin with 😅 was a bit rushed
