### ISSUE TITLE
things to add/fix to 3arthh4ack

### ISSUE THREAD

**Issue by master7720** [3arthqu4ke/3arthh4ck#14]
AutoCrystal - timmings/Inhibit/raytracebypass

Surround - timmings/renders

AutoArmor - timmings

AutoTrap timmings/renders

Offhand - timmings

Chams - WireframeWidth

KillAura - fix kick error/some render settings/timmings

HudEditer - fix it

**Comment by master7720** [comment]
send messages here if i missed sum

**Comment by threevt** [comment]
Would be nice if you could explain your suggestions to what they are as timings and some render settings do not help

**Comment by 3arthqu4ke** [comment]
Yeah no clue what any of this is.

**Comment by master7720** [comment]
will redo this later rn i am in school at theses dells pc's suck

**Comment by zb0bb** [comment]
@master7720 school on a Sunday :(

**Comment by GentlemanMC** [comment]
hudeditor works u just need to bind it and press the keybind out of the clickgui

**Comment by 3arthqu4ke** [comment]
Reopen or make a new issue when you are ready.

**Comment by master7720** [comment]
> @master7720 school on a Sunday :(

it was friday for me

**Comment by GurteX** [comment]
trash timings fan (AUTOARMOR TIMINGS GO BRRR)
