### ISSUE TITLE
CrystalAura render

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#143]
Add an movement for render so that whenever the crystal placed the render will move to that place
the same as zaelo crystal render
-thanks for reading-

**Comment by 3arthqu4ke** [comment]
> zaelo crystal render

what? u got a video? u mean where the box like slides from position to position?

**Comment by Random3131** [comment]
> > zaelo crystal render
> 
> what? u got a video? u mean where the box like slides from position to position?

probably

**Comment by AnotherNoName** [comment]
> Add an movement for render so that whenever the crystal placed the render will move to that place the same as zaelo crystal render -thanks for reading-

u mean something like what TrollHack ZealotCrystal+ does? (like this: https://m.bilibili.com/video/BV12R4y1F7GJ)

**Comment by zb0bb** [comment]
> > Add an movement for render so that whenever the crystal placed the render will move to that place the same as zaelo crystal render -thanks for reading-
> 
> u mean something like what TrollHack ZealotCrystal+ does? (like this: https://m.bilibili.com/video/BV12R4y1F7GJ)

Looks ugly

**Comment by peef609** [comment]
> > zaelo crystal render
> 
> what? u got a video? u mean where the box like slides from position to position?

**Comment by JOniGod** [comment]
> > 扎埃洛水晶渲染
> 
> 什么？你有视频吗？你的意思是盒子像从一个位置滑到另一个位置？

https://www.youtube.com/watch?v=3_ro-0hIbhs 
Render higher difficulty
client is trollhack the sexmaster have the same

**Comment by JOniGod** [comment]
https://www.youtube.com/watch?v=3_ro-0hIbhs 
Render just like trollhack 
and sexmaster have same
https://github.com/Luna5ama/TrollHack

**Comment by 3arthqu4ke** [comment]
Preview here https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2928411167
