### ISSUE TITLE
[FEATURE] Add Glow and Outline option to HoleESP

### ISSUE THREAD

**Issue by AnotherNoName** [3arthqu4ke/3arthh4ck#149]
Add an option to HoleESP to have an Outline and Glow render for this one, just like [TrollHack](https://github.com/Luna5ama/TrollHack) or [gs++](https://github.com/TechAle/gsplusplus) does.

***Example:***
![ss](https://user-images.githubusercontent.com/65259492/186798392-9ee92a5e-cec7-4177-bed2-f05618bf9b31.png)

**Comment by Zane2b2t** [comment]
the trollhack kids :rofl: ur hole esp is shit but yes i agree add Glow option to hole esp like the old phobos

**Comment by AnotherNoName** [comment]
> the trollhack kids 🤣 ur hole esp is shit but yes i agree add Glow option to hole esp like the old phobos

thats not my holeesp btw, and ik it sucks
