### ISSUE TITLE
[FEATURE] Project License

### ISSUE THREAD

**Issue by mdo992** [3arthqu4ke/3arthh4ck#150]
It would be nice if you could add a license to this project instead of leaving it unlicensed.

**Comment by 3arthqu4ke** [comment]
Did you think about a specific one? I thought about GPL 3

**Comment by mdo992** [comment]
> Did you think about a specific one? I thought about GPL 3

It’s your project so you license it however you want. But if you want to know what I had in mind it was the MIT license.

**Comment by cattyngmd** [comment]
wtfpl license is the best

**Comment by 3arthqu4ke** [comment]
I like MIT better too, but theres uhhhhhhhhhhhhhh reasons

**Comment by 3arthqu4ke** [comment]
Actually nvm

**Comment by mdo992** [comment]
Thanks!
