### ISSUE TITLE
[FEATURE] OffHand - SwordGapIgnoreHealth option

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#152]
add oyvey offhand

**Comment by 3arthqu4ke** [comment]
why?

**Comment by 3arthqu4ke** [comment]
Like what are you missing in the current Offhand???

**Comment by Random3131** [comment]
> add oyvey offhand

💀

**Comment by peef609** [comment]
yeah I want the offhand has swordgapple which isn't affected by health
like you can eat gap even the hp is lower than offhand health

**Comment by GurteX** [comment]
retard

**Comment by peef609** [comment]
monke

**Comment by peef609** [comment]
> retard

monkey

**Comment by 3arthqu4ke** [comment]
> yeah I want the offhand has swordgapple which isn't affected by health like you can eat gap even the hp is lower than offhand health

thats kinda missing the point of offhand health? if you want to gap while your hp is lower than offhand health you should turn your offhand health down?

**Comment by 3arthqu4ke** [comment]
I guess I could make an override setting...

**Comment by peef609** [comment]
then I

> > yeah I want the offhand has swordgapple which isn't affected by health like you can eat gap even the hp is lower than offhand health
> 
> thats kinda missing the point of offhand health? if you want to gap while your hp is lower than offhand health you should turn your offhand health down?

then it can kill me when it explodes when the health is lower than 16

**Comment by Zane2b2t** [comment]
> 

There's nothing missing, oyvey offhand has 2 settings and works as good as phobos offhand, oyvey offhand is just good and so much easier to config
phobos offhand complicated ASF
