### ISSUE TITLE
[Logout spots chams]

### ISSUE THREAD

**Issue by xyzbtw** [3arthqu4ke/3arthh4ck#153]
"Ghost" chams that are left there after the player logs out like in the ss where he is logged out, but I still have the chams on my screen

![2022-07-23_16 33 48](https://user-images.githubusercontent.com/89705569/186928418-5b766461-9c63-446e-94a7-65805ecd5eed.png)

**Comment by 3arthqu4ke** [comment]
Could suggestion, please also check out the ExtraTab ping: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2936382093
