### ISSUE TITLE
[Skycolor]

### ISSUE THREAD

**Issue by xyzbtw** [3arthqu4ke/3arthh4ck#154]
Changeable skycolor for every dimension (nether, ow, end)

**Comment by 3arthqu4ke** [comment]
Have you tried changing it with ResourcePacks :)

**Comment by xyzbtw** [comment]
Nope, I haven't

**Comment by GurteX** [comment]
genius

**Comment by xyzbtw** [comment]
Ill just try adding skycolor through a plugin then
