### ISSUE TITLE
[FEATURE] Docker Entrypoint

### ISSUE THREAD

**Issue by 3arthqu4ke** [3arthqu4ke/3arthh4ck#159]
Currently we need to open the shell of the docker container and type in commands which is ok I guess but could be better. I really like what has been done [here](https://github.com/Edouard127/HeadlessMc), at least if it does what I think it does. I would still like to keep the option to use pingbypass as a base image, maybe ignoring the args from the docker-compose.yml, not sure if that works the way I imagine it, research is needed.

**Comment by 3arthqu4ke** [comment]
Seems like it is currently not possible to remove args from the docker-compose.yml via the docker-compose.override.yml. See  #3729 in the docker compose repo.

**Comment by 3arthqu4ke** [comment]
We could deploy a second type of image with the compose yml to github pages?

**Comment by TerikKek** [comment]
It is possible depending on how the hmc login <email> command works. You may be able to deploy the docker container with env variables and then just modify the container crap to make it use env as default for the login stuff. Only issue is that then password isn't really secure.
