### ISSUE TITLE
ESP/Shaderesp conflict

### ISSUE THREAD

**Issue by lyricnight** [3arthqu4ke/3arthh4ck#16]
When you enable ESP and disable 'Player', then if you enable ShaderESP (the separate plugin) and set it to display over players, it does not display anything.

**Comment by RealzPrestige** [comment]
loser

**Comment by lyricnight** [comment]
thanks prestige

**Comment by ZenovJB** [comment]
> loser

lel incel spotted

**Comment by 3arthqu4ke** [comment]
Sorry but I don't support the plugins anymore, maybe u can get someone to use recaf or something to remove the if statement causing ShaderESP not to do anything while ESP is enabled.
