### ISSUE TITLE
Create more version of 3arthh4ck 

### ISSUE THREAD

**Issue by CreeperBois** [3arthqu4ke/3arthh4ck#160]
**Is your feature request related to a problem? Please describe.**
Its frustating when the server is on the newer version and beacuse of earthhack being on 1.12 it glictches out at somepint as the meachanics dont match the server mechanics

**Describe the solution you'd like**
Make versions of earthhack for more mc versions but dont discontinue 1.12 version
**Describe alternatives you've considered**
Other newer verion clients clients

**Additional context**
But no other client has so much powerful crystal aura as earthhack does

**Comment by 3arthqu4ke** [comment]
I would like to, but updating is a lot of work.

**Comment by CreeperBois** [comment]
like take time to update and then release versions

**Comment by Zane2b2t** [comment]
> I would like to, but updating is a lot of work.

Hire someone frfr

**Comment by Zane2b2t** [comment]
> **Is your feature request related to a problem? Please describe.** Its frustating when the server is on the newer version and beacuse of earthhack being on 1.12 it glictches out at somepint as the meachanics dont match the server mechanics
> 
> **Describe the solution you'd like** Make versions of earthhack for more mc versions but dont discontinue 1.12 version **Describe alternatives you've considered** Other newer verion clients clients
> 
> **Additional context** But no other client has so much powerful crystal aura as earthhack does

use via version
