### ISSUE TITLE
Crystal Extrap[BUG]

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#161]
I set the extrap to 6 or higher，killaura will place crystals in abnormal positions
https://www.youtube.com/watch?v=mM3nXoPX4-8

**Comment by 3arthqu4ke** [comment]
Can you turn on RenderExtrapolation? I do not see why it would extrapolate when he is not moving

**Comment by 3arthqu4ke** [comment]
Could you see what happens if you recreate the same Situation but with AntiPackets - SEntityVelocity on?

**Comment by JOniGod** [comment]
> 你能看到如果你重新创建相同的情况，但使用AntiPackets - SEntityVelocity会发生什么吗？
> 
> 编辑：并确保数据包 - 快速速度在执行此操作时关闭。

https://youtu.be/3pcqHKRH8-4

> Could you see what happens if you recreate the same Situation but with AntiPackets - SEntityVelocity on?
> 
> Edit: and make sure that Packets - Fast-Velocity is off when you do that.

https://youtu.be/3pcqHKRH8-4
not solved

**Comment by 3arthqu4ke** [comment]
Thank you, I will look into it.

**Comment by JOniGod** [comment]
> Thank you, I will look into it.

ok thankyou

**Comment by 3arthqu4ke** [comment]
Can you check if its resolved here: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2939018469
