### ISSUE TITLE
[FEATURE] Make BlockLag support other block types

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#166]
add optional blocks for blocklag include skull.

**Comment by GRIFFiin** [comment]
and piston

**Comment by Zane2b2t** [comment]
Make it with the blacklist/whitelist type thing in most modules

**Comment by JOniGod** [comment]
I think it's a good idea, some servers patch obby burrow, but not other blocks, I think this suggestion brings more practicality
