### ISSUE TITLE
[FEATURE] Range for Crystal Chams (and maybe other render modules)

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#167]
Add range in nametags and crystal chams so it wont render the nametags  or crystals if they are out of the range

**Comment by 3arthqu4ke** [comment]
Theres already a Nametag range.

**Comment by Random3131** [comment]
my bad

**Comment by Zane2b2t** [comment]
Much needed there's sometimes crystals 1000000000 blocks away that i dont want to see

**Comment by Random3131** [comment]
btw what client's shader esp were you using in your montage 3arthqu4ke?
