### ISSUE TITLE
[FEATURE] Holefill render

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#168]

**Comment by Zane2b2t** [comment]
Trollhack rename :rofl:

**Comment by JOniGod** [comment]
> Trollhack rename 🤣

😅

**Comment by 3arthqu4ke** [comment]
Hmm, you can see the HoleESP disappearing when a hole gets filled, not enough ? :(

**Comment by JOniGod** [comment]
> Hmm, you can see the HoleESP disappearing when a hole gets filled, not enough ? :(
alr，although it's not obvious, I just think that the render of holefill will make the player react better, if my suggestion is not good, then I'm really sorry my bad ;-;

**Comment by 3arthqu4ke** [comment]
No it is fine, an ESP option for AutoTrap could be cool too.

**Comment by JOniGod** [comment]
Thanks i will enjoy it
