### ISSUE TITLE
MY FRIDGE IS BURNING

### ISSUE THREAD

**Issue by GurteX** [3arthqu4ke/3arthh4ck#17]
DWKJNJWNDJNSJDNWNDJNSNDJNWJNDNSKJDFNHWKBSDNHWJHVDNWVDSHJNKVHWNDJHSJVNHDHWKJVSHNHSDVNHBJKBWVNSHVJDGCHXZJHCHWVUHISXUDCHNVQHUVNHOSXHCNVIUWNHHAVJHNXUCHUVQHUHUSKXZCKJVHQWHJVHJZXCHKVHCGWIVHZ

**Comment by GurteX** [comment]
it stopped burning.

**Comment by Rat2b2t** [comment]
kek
