### ISSUE TITLE
[BUG] cosmos rotation compatibility

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#170]
**Describe the bug**  
Phobos conflicting with cosmos ca
**To Reproduce**  
1. use phobos and turn on cosmos ca with rotate on lol
2. it no work :o
**Expected behavior**  
A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in.
Rotations conflicting just like with future, Add cosmos support to "**compablity**" module
**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you!

**Additional context**  
Fix plz :pray: 
**Checklist**
- [x] I know how to properly use check boxes.
- [ ] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
Does cosmos ca work with future?

**Comment by threevt** [comment]
ratio

**Comment by Zane2b2t** [comment]
> Does cosmos ca work with future?

idk try it out

**Comment by 3arthqu4ke** [comment]
We will see what happens here: https://github.com/momentumdevelopment/cosmos/issues/255
