### ISSUE TITLE
[FEATURE] ClickGui - Custom background and size

### ISSUE THREAD

**Issue by cmetanamaker** [3arthqu4ke/3arthh4ck#175]
Custom background and size of ClickGui

**Comment by amendoa657** [comment]
Rusher enjoyer

**Comment by cmetanamaker** [comment]
No, I just think ClickGui is too big.

**Comment by Zane2b2t** [comment]
> No, I just think ClickGui is too big.

yes.

**Comment by agua420** [comment]
add this please

**Comment by eret0007** [comment]
Cool background animation like rusher has would be really cool to have

**Comment by 3arthqu4ke** [comment]
What does that look like? Like in the Main menu gui just with a picture/animation?

**Comment by Random3131** [comment]
> What does that look like? Like in the Main menu gui just with a picture/animation?

basically yes

**Comment by Zane2b2t** [comment]
> What does that look like? Like in the Main menu gui just with a picture/animation?

He wants instead of just blur or nothing as gui background add black background to gui or maybe fading colors, Also add a changeable size to clickgui

**Comment by mdo992** [comment]
this would be better off as a plugin

**Comment by 3arthqu4ke** [comment]
Some conversation happened in #177

**Comment by Eralp232** [comment]
3arth can u add clickgui scale?

**Comment by agua420** [comment]
clickgui scale when
