### ISSUE TITLE
[BUG] Crashes with Konas

### ISSUE THREAD

**Issue by eret0007** [3arthqu4ke/3arthh4ck#176]
1.8.1 crashes with konas error code is 1 there is no crashlog idk what to do

**Comment by Zane2b2t** [comment]
> 

wdym there's no crash log?
goto 

%AppData%\Roaming\.minecraft\logs and send latest.txt
also if youre using cracked konas what r u doing.

**Comment by 3arthqu4ke** [comment]
What do you miss from konas?

**Comment by threevt** [comment]
konas hasnt been updates since 2021 and the beta hasnt been updates since jan. not much of a reason to still use the client
