### ISSUE TITLE
What does that look like? Like in the Main menu gui just with a picture/animation?

### ISSUE THREAD

**Issue by cmetanamaker** [3arthqu4ke/3arthh4ck#177]
I meant that it would be possible to change the color and transparency of the clickgui background

**Comment by cmetanamaker** [comment]
sorry for the inaccuracy

**Comment by Zane2b2t** [comment]
> I meant that it would be possible to change the color and transparency of the clickgui background

Also add costum main menu like old phobos

**Comment by cmetanamaker** [comment]
yeah that would be nice too

**Comment by mdo992** [comment]
> Also add costum main menu like old phobos

ill try making it a plugin rn

**Comment by zb0bb** [comment]
> > Also add costum main menu like old phobos
> 
> ill try making it a plugin rn

Y'all are fucking stupid
https://github.com/3arthqu4ke/3arthh4ck/tree/plugins/phobosgui

**Comment by mdo992** [comment]
> Y'all are fucking stupid https://github.com/3arthqu4ke/3arthh4ck/tree/plugins/phobosgui

did you even check that

**Comment by 3arthqu4ke** [comment]
Closing this to bring discussion back to #175
