### ISSUE TITLE
[BUG] Chunkloading bug with Rusherhack

### ISSUE THREAD

**Issue by GentlemanMC** [3arthqu4ke/3arthh4ck#18]
![image](https://user-images.githubusercontent.com/76640636/163718188-0eca6c7f-4fa5-44e1-9376-9a40ca2f705a.png)
![image](https://user-images.githubusercontent.com/76640636/163718190-4dd545c5-afbc-4c7d-92e0-48987fef12d2.png)
![image](https://user-images.githubusercontent.com/76640636/163718192-f9459ca1-8576-41e6-a722-5df0b868b91a.png)
 im only using rusherhack with it (the bug didnt use to exist in 1.4.0)

**Comment by GentlemanMC** [comment]
btw when i used the jar from this commit https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2178000035
it worked just fine

soooo...
i think u broke it instead of fixing it

**Comment by GentlemanMC** [comment]
i think u should revert that "fixes" commit because the issue is stupid af and no one would even notice it

**Comment by 3arthqu4ke** [comment]
Do you use SettingSpoof? Whats your render distance?

**Comment by GentlemanMC** [comment]
> Do you use SettingSpoof? Whats your render distance?

lol my render distance is 8

**Comment by GentlemanMC** [comment]
also one of my friends has the same issue

**Comment by GentlemanMC** [comment]
we are both not using the settingspoof module
we also tried to disable every module and we still have the issue

**Comment by NegroFighter69420** [comment]
happens to me with no modules enabled

**Comment by GentlemanMC** [comment]
yeah me too

**Comment by GentlemanMC** [comment]
@NegroFighter69420 whats ur gpu?

**Comment by NegroFighter69420** [comment]
idk

**Comment by NegroFighter69420** [comment]
Intel(R) HD Graphics 520
playing on a laptop lol

**Comment by GentlemanMC** [comment]
same...

**Comment by Sandwich4780** [comment]
> we are both not using the settingspoof module
> we also tried to disable every module and we still have the issue

Have you tried loading a different config? Maybe load the default config and see if that fixes the issue.

**Comment by GentlemanMC** [comment]
> > we are both not using the settingspoof module
> > we also tried to disable every module and we still have the issue
> 
> Have you tried loading a different config? Maybe load the default config and see if that fixes the issue.

i tried and it didnt work
i think this issue is only present in integrated gpus

**Comment by Sandwich4780** [comment]
> > > we are both not using the settingspoof module
> > > we also tried to disable every module and we still have the issue
> > 
> > 
> > Have you tried loading a different config? Maybe load the default config and see if that fixes the issue.
> 
> i tried and it didnt work i think this issue is only present in integrated gpus

I use intergraded graphics and I don’t have this issue.

**Comment by NegroFighter69420** [comment]
i dont think its a issue with rusherhack since i am having this issue and not using it

**Comment by 3arthqu4ke** [comment]
And it really doesn't exist in 1.4.0? I need to check, but I don't think I added something that could break something since then.

**Comment by GentlemanMC** [comment]
> And it really doesn't exist in 1.4.0? I need to check, but I don't think I added something that could break something since then.

yep

**Comment by GentlemanMC** [comment]
1.4.0 is fine

**Comment by GentlemanMC** [comment]
me and this man have the exact same issue

**Comment by Sandwich4780** [comment]
> i dont think its a issue with rusherhack since i am having this issue and not using it

Are you using any other clients with 3arthh4ck? I can’t get this issue to happen to me.

**Comment by NegroFighter69420** [comment]
nope just earthhack and optifine

**Comment by GentlemanMC** [comment]
same^^

**Comment by GentlemanMC** [comment]
lmfao
when i loaded future with it the bug got fixed

**Comment by NegroFighter69420** [comment]
sadly i have no future 😔

**Comment by 3arthqu4ke** [comment]
Ok not sure if I can fix this, could you give me logs of you loading Minecraft and joining a server with 3arthh4ck+Rusherhack and 3arthh4ck + Future + Rusherhack? Is this 100% reproducible?

**Comment by Sandwich4780** [comment]
> > i dont think its a issue with rusherhack since i am having this issue and not using it
> 
> Are you using any other clients with 3arthh4ck? I can’t get this issue to happen to me.

This issue just happened to me, i’m not sure how though as I didn’t change anything.

**Comment by GentlemanMC** [comment]
once i get on my pc ill give u the logs

**Comment by Nope0xAL4TAC** [comment]
yall stupid its ur render distance 💀

**Comment by Sandwich4780** [comment]
> yall stupid its ur render distance 💀

He said his render distance was at 8...

**Comment by 3arthqu4ke** [comment]
Could you check if the issue still persists in [this](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2189554076) release?
Also it would be nice if you could check if the fix didn't break the previously gained compatibility with future.

**Comment by GentlemanMC** [comment]
it works fine
