### ISSUE TITLE
[FEATURE] Stairs mode setting for CA

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#183]
Might be a bad idea but we wont know unless its actually made
In stairs espechially on strict servers by the time the crystals break the enemy has already went down like 2 blocks taking no damage

With this setting it can predict which direction its going i guess? And placing the crystal 1 block bellow the enemy is so when he goes down he takes max damage

**Comment by 3arthqu4ke** [comment]
Have you tried out Extrapolation for stairs?

**Comment by Random3131** [comment]
> Might be a bad idea but we wont know unless its actually made In stairs espechially on strict servers by the time the crystals break the enemy has already went down like 2 blocks taking no damage
> 
> With this setting it can predict which direction its going i guess? And placing the crystal 1 block bellow the enemy is so when he goes down he takes max damage

Extrapolation works just fine

**Comment by Random3131** [comment]
however there is an issue with extrapolate that only occurs on stairs i.e. the ca starts multi placing doesn't happens on ground only on stairs https://streamable.com/hsqe8u

**Comment by Random3131** [comment]
https://pastebin.com/7n8HQTe6 ca config

**Comment by Random3131** [comment]
https://pastebin.com/ziSj852M ca config (was using existed 200 to make the issue more visible)

**Comment by Zane2b2t** [comment]
> 

yeah the multiplacing is annoying

**Comment by Zane2b2t** [comment]
> 

will try :pray:
i dont even use phobos ca lol
