### ISSUE TITLE
[FEATURE] Auto Armor repair

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#184]

**Comment by xyzbtw** [comment]
What do you mean by this? As in so it automatically takes off when mending and on when done mending?

**Comment by 3arthqu4ke** [comment]
There is a take off option in AutoArmor. I am not sure what could be made more "Auto", maybe it exping for you, but with middle click exp thats literally just holding down one button.

**Comment by Zane2b2t** [comment]
already a thing

**Comment by GurteX** [comment]
bro wants to be an AI
