### ISSUE TITLE
Fix Rotations Compatibility With Future

### ISSUE THREAD

**Issue by HausemasterIssue** [3arthqu4ke/3arthh4ck#19]
When using Future with 3arthh4ck, the rotations are completely fucked. When sitting in a boat, you are facing backwards, when using AutoCrystal with rotations on, it dosen't rotate, you gotta look at block you want it to place at.

Very likely has to do with rotation mixins so fix your shit please and thanks.

**Comment by Sandwich4780** [comment]
Are you using the compatibility module?

**Comment by GentlemanMC** [comment]
kek

**Comment by lyricnight** [comment]
> When using Future with 3arthh4ck, the rotations are completely fucked. When sitting in a boat, you are facing backwards, when using AutoCrystal with rotations on, it dosen't rotate, you gotta look at block you want it to place at.
> 
> Very likely has to do with rotation mixins so fix your shit please and thanks.

There's literally a module called 'Compatability' in the client section....

**Comment by GentlemanMC** [comment]
and the description of that module is "fixes rotations compatibility with future"

> > When using Future with 3arthh4ck, the rotations are completely fucked. When sitting in a boat, you are facing backwards, when using AutoCrystal with rotations on, it dosen't rotate, you gotta look at block you want it to place at.
> > Very likely has to do with rotation mixins so fix your shit please and thanks.
> 
> There's literally a module called 'Compatability' in the client section....

**Comment by 3arthqu4ke** [comment]
Yeh turn that module on. Futures rotations will still have priority but 3arthh4cks won't be broken anymore. Sometime I might make a setting that lets us prioritize our rotations.
