### ISSUE TITLE
[BUG] AutoCrystal Extrapolation STILL goes through walls

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#190]
If the enemy enters the hole and
![Q4IBVA6C@__TAU~%_SV{9@8](https://user-images.githubusercontent.com/92873946/187273672-2c8a7aab-7d6e-4da2-9d44-f93556daf963.png)
 is moving very fast, extrap will calculate another location (outside the hole)
https://youtu.be/hZevRkxU8vc

**Comment by Zane2b2t** [comment]
i suggested something like that for stairs

**Comment by 3arthqu4ke** [comment]
Try PushOutOfBlocks Mode MP, I think, at least not None. It should be enabled by default I will fix that. Tell me if that helps.

**Comment by JOniGod** [comment]
Other locations will still be calculated
![XCT)5YMA1D(FIN%RVAX0G`P](https://user-images.githubusercontent.com/92873946/187318614-f2c9e0e4-5d19-420a-91ae-39dd5e06299e.png)

**Comment by 3arthqu4ke** [comment]
Not sure what Im seeing on that SS, it looks like the tracer showing the predicted position is inside the hole.

**Comment by JOniGod** [comment]
I don't mean that. I'll give an example. Once I was playing duel. In the middle of the game, my enemy hit the wall at high speed, but my extrap directly calculates the block behind the wall, which made me miss killing him chance, what I want to ask you to fix is: the problem of the deviation of the enemy's calculation when moving at high speed. plz

**Comment by Zane2b2t** [comment]
> 

Video is private, make it unlisted

**Comment by JOniGod** [comment]
oh my bad

**Comment by 3arthqu4ke** [comment]
I see, I can recreate this. I will look into it.

**Comment by 3arthqu4ke** [comment]
Please try out this version https://github.com/3arthqu4ke/3arthh4ck/runs/8131318657 it has much better extrapolation

**Comment by JOniGod** [comment]
crystal extrap is good now thank you
