### ISSUE TITLE
[FEATURE] Alpha & outline setting for ShaderChams

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#191]
will look like this
![2022-08-29_21 25 17](https://user-images.githubusercontent.com/88916121/187285260-805e2e1e-870b-413a-8eac-8bc9ce6d723a.png)
![2022-08-29_21 17 55](https://user-images.githubusercontent.com/88916121/187285287-97909878-5e58-483c-abec-f8c59a100ec2.png)
![2022-08-29_21 19 32](https://user-images.githubusercontent.com/88916121/187285320-5b1e6792-4519-4d17-abc5-ee569d04fb44.png)

Shaderchams are flat and ugly asf currently, Please make evolution :pray:

**Comment by Zane2b2t** [comment]
@cattyngmd :pray:

**Comment by cattyngmd** [comment]
> @cattyngmd 🙏

maybe :D

**Comment by Zane2b2t** [comment]
zamn, here's another screenshot https://cdn.discordapp.com/attachments/1005969365981741096/1014623690987675809/unknown.png

**Comment by Zane2b2t** [comment]
![2022-09-01_02 46 01](https://user-images.githubusercontent.com/88916121/187809349-cb3e1fbf-4e40-49a5-9d90-47f63e028ada.png)
![2022-09-01_02 46 09](https://user-images.githubusercontent.com/88916121/187809362-65f030e8-55c8-48d0-9f1e-f7c2e20af99d.png)

@3arthqu4ke make "chams" always render on top of "ESP" so the shaderchams overlay the player instead of nothing, idk if u want that or not just saying

also fix this

![2022-09-01_02 42 42](https://user-images.githubusercontent.com/88916121/187809468-b14ccc2e-c345-46b9-8b89-d848e029474f.png)
![2022-09-01_02 42 09](https://user-images.githubusercontent.com/88916121/187809476-5f3799ba-ca53-484c-9e42-4c1b7aed02df.png)

**Comment by Zane2b2t** [comment]
(That's 1.8.2 from https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2967408806/workflow btw)

**Comment by Zane2b2t** [comment]
also bring back shaderchams for crystals

**Comment by 3arthqu4ke** [comment]
> @3arthqu4ke make "ESP" always render on top of "chams" so the shaderchams overlay the player instead of nothing, idk if u want that or not just saying

I think you can achieve that by turning on Chams after ESP or the other way around.

**Comment by Zane2b2t** [comment]
> > @3arthqu4ke make "ESP" always render on top of "chams" so the shaderchams overlay the player instead of nothing, idk if u want that or not just saying
> 
> I think you can achieve that by turning on ESP after Chams or the other way around.

Yeah that happend
