### ISSUE TITLE
[FEATURE] stop CA if eating

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#192]
**Is your feature request related to a problem? Please describe.**
On some servers you can't use multitask, so with offhand or silentswitch you can't eat

**Describe the solution you'd like**
Add the option to stop placing/breaking if eating instead of having to manually turn off CA

**Additional context**
https://streamable.com/uf2dux

**Comment by Zane2b2t** [comment]
why not just mainhand

**Comment by Random3131** [comment]
Config issue

**Comment by Ai2473** [comment]
> why not just mainhand

Why yes

**Comment by xyzbtw** [comment]
> why not just mainhand

cause for example when you do mainhand, but have autoswitch on, it still doesn't let you eat properly

**Comment by Zane2b2t** [comment]
> 

dont use autoswitch is it hard to press 1 button?

**Comment by xyzbtw** [comment]
> > 
> 
> dont use autoswitch is it hard to press 1 button?

not hard that's why I just turn off ca

**Comment by Zane2b2t** [comment]
> 

i mean pressing the crystal bind on ur hotbar but ok
