### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GurteX** [3arthqu4ke/3arthh4ck#194]
Write a silent switch bypass bro 

that will be funny 🛌

**Comment by Zane2b2t** [comment]
Write a fly bypass bro
that will be funny

**Comment by GurteX** [comment]
> Write a fly bypass bro
> that will be funny

stfu and stop being annoying asf

**Comment by cattyngmd** [comment]
> Write a silent switch bypass bro
> 
> that will be funny 🛌

cooldown bypass already exists

**Comment by GurteX** [comment]
> > Write a silent switch bypass bro
> > 
> > that will be funny 🛌
> 
> cooldown bypass already exists

and it doesnt work as bypass just randomly switches items in my hotbar

**Comment by 3arthqu4ke** [comment]
For Mode Pick you need Sorter - VirtualHotbar.

**Comment by GurteX** [comment]
> For Mode Pick you need Sorter - VirtualHotbar.

why do i need that if it doesnt work

**Comment by 3arthqu4ke** [comment]
Works for me.

**Comment by Zane2b2t** [comment]
> 

btw can u teatch me how to use sorter? i made inventory layout, did +sorter save bingo and turned on hotbar and inventory
and then +sorter load bingo, but it barearly works and when i open and close server it doesnt work

is this module supposed to sort inventory or what

**Comment by GurteX** [comment]
> > 
> 
> btw can u teatch me how to use sorter? i made inventory layout, did +sorter save bingo and turned on hotbar and inventory
> and then +sorter load bingo, but it barearly works and when i open and close server it doesnt work
> 
> is this module supposed to sort inventory or what

it is, set delay to 50-150
