### ISSUE TITLE
[FEATURE] Wiframe render

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#195]
add wiframe render for player
![image](https://user-images.githubusercontent.com/97225256/187708385-5e83cc23-da1b-4999-8eeb-c03e64ed3369.png)

**Comment by Zane2b2t** [comment]
I think its already thing not sure, if u set FILL alpha in chams (if it exists) to 0 and set outline alpha to 100 u will get wireframes, not sure if these settings exist tho

**Comment by peef609** [comment]
> I think its already thing not sure, if u set FILL alpha in chams (if it exists) to 0 and set outline alpha to 100 u will get wireframes, not sure if these settings exist tho

doesn't exist this method, I think this render can add into earthhack as a specific module

**Comment by Zane2b2t** [comment]
> 

this will cause bloat.
