### ISSUE TITLE
[FEATURE] Make viewmodel of phobos compatible with future (if it's even possible)

### ISSUE THREAD

**Issue by pastacat48** [3arthqu4ke/3arthh4ck#199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zb0bb** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Use smallshield in future to lower the offhand

**Comment by BebSxy** [comment]
that just lowers his position LOL
