### ISSUE TITLE
[FEATURE] Surround

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#204]
add PacketPlace for surround, that will make it be faster

**Comment by GurteX** [comment]
its already packet retard

**Comment by peef609** [comment]
> its already packet retard

slow packet monke

**Comment by GurteX** [comment]
config issue + skill issue + iq issue

**Comment by peef609** [comment]
> config issue + skill issue + iq issue

monke issue

**Comment by 3arthqu4ke** [comment]
Packet will not increase speeds. Rotate - Packet will do maybe on rotate servers but thats it.
