### ISSUE TITLE
[BUG] Crystal damgerender

### ISSUE THREAD

**Issue by AlexanderJonny** [3arthqu4ke/3arthh4ck#205]
crystaldmgrender doesn't work when I turn on fade
![JDC1Q)`$T 0GWN 6C3G5{KH](https://user-images.githubusercontent.com/92873946/188067224-55ba81b9-919f-41dd-892e-d0e3a8758204.png)
![83I(RL5$OP7U}33BX91(5 C](https://user-images.githubusercontent.com/92873946/188067235-a28f1e89-62cb-4dd1-8c5a-73aa56aea8a8.png)

**Comment by 3arthqu4ke** [comment]
What if you use Fade-Compatibility?

**Comment by JOniGod** [comment]
If i use ade-Compatibility dmg it will show normal
But after turning on fade-com the render color will be darker, I don't like it

**Comment by 3arthqu4ke** [comment]
ok will fix when i have time

**Comment by JOniGod** [comment]
k
