### ISSUE TITLE
[FEATURE] Wiframe chams

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#208]
make wireframe chams can be disabled for animals and monsters

**Comment by Zane2b2t** [comment]
wiframe

**Comment by Zane2b2t** [comment]
thats already a thing :brain:

**Comment by 3arthqu4ke** [comment]
Stop making suggestions for stuff thats already in the client?

**Comment by Random3131** [comment]
he is right, you cant disable wireframe for animals even tho you have animals off in chams
![2022-09-02_22 16 29](https://user-images.githubusercontent.com/103523147/188201009-efda0226-96cc-4cfd-9525-3ce555910db4.png)

**Comment by Random3131** [comment]
![2022-09-02_22 16 34](https://user-images.githubusercontent.com/103523147/188201148-e9516cf9-9420-4b26-80ba-74d36f25f958.png)

**Comment by Random3131** [comment]
![2022-09-02_22 19 57](https://user-images.githubusercontent.com/103523147/188201431-91584642-88df-4a73-8826-b948a470f249.png)
it still renders animals and other mobs

**Comment by 3arthqu4ke** [comment]
😡

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2980653728 I hate being wrong!
