### ISSUE TITLE
[FEATURE] Sword-Gapple switch

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#212]
Make sword-gapple work with crystals and not only with totem in your offhand

**Comment by GRIFFiin** [comment]
just use crystals on offhand and gaps mainhand

**Comment by Zane2b2t** [comment]
> just use crystals on offhand and gaps mainhand

:brain: youre 100% a 6b player

**Comment by Random3131** [comment]
> just use crystals on offhand and gaps mainhand

Did u even read what u wrote?

**Comment by Zane2b2t** [comment]
> > just use crystals on offhand and gaps mainhand
> 
> Did u even read what i wrote?

he's a 6b player dont argue with him

**Comment by master7720** [comment]
> > > just use crystals on offhand and gaps mainhand
> > 
> > 
> > Did u even read what i wrote?
> 
> he's a 6b player dont argue with him

my mans talking to himself

**Comment by GRIFFiin** [comment]
> > just use crystals on offhand and gaps mainhand
> 
> 🧠 youre 100% a 6b player

nope wrong server

**Comment by GRIFFiin** [comment]
> > > just use crystals on offhand and gaps mainhand
> > 
> > 
> > Did u even read what i wrote?
> 
> he's a 6b player dont argue with him

retard

**Comment by Zane2b2t** [comment]
> 

🤡
