### ISSUE TITLE
Surround/City ESP[FEATURE]

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#215]
Know clearly the city location of the enemy, as shown in the picture
![_{ANEHIBI MW(Z~NMGBSB%2](https://user-images.githubusercontent.com/92873946/188251071-4af87df8-d52c-478b-9c49-8418385280f5.jpg)
![1QC0LEFEBYICNI5`T19`RB6](https://user-images.githubusercontent.com/92873946/188251073-57f7349e-9d73-4838-9b1c-81f20df5df08.jpg)
![GL9_LRQT7% ACBBB%ZD}7DQ](https://user-images.githubusercontent.com/92873946/188251075-f6b54ddd-b2ac-48d9-866d-074251f545f3.jpg)

**Comment by JOniGod** [comment]
// Decompiled with: CFR 0.152
// Class Version: 8
package me.moon.features.modules.render;

import java.awt.Color;
import me.moon.event.events.Render3DEvent;
import me.moon.features.modules.Module;
import me.moon.features.setting.Setting;
import me.moon.util.EntityUtil;
import me.moon.util.RenderUtil;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;

public class SurroundRender
extends Module {
    public EntityPlayer target;
    private final Setting<Integer> range = this.register(new Setting<Integer>("Range", 5, 1, 10));

    public SurroundRender() {
        super("SurroundRender", "SurroundRender", Module.Category.RENDER, true, false, false);
    }

    @Override
    public void onRender3D(Render3DEvent event) {
        if (SurroundRender.fullNullCheck()) {
            return;
        }
        this.target = this.getTarget(this.range.getValue().intValue());
        this.surroundRender();
    }

    private void surroundRender() {
        if (this.target != null) {
            Vec3d a = this.target.func_174791_d();
            if (SurroundRender.mc.field_71441_e.func_180495_p(new BlockPos(a)).func_177230_c() == Blocks.field_150343_Z || SurroundRender.mc.field_71441_e.func_180495_p(new BlockPos(a)).func_177230_c() == Blocks.field_150477_bB) {
                RenderUtil.drawBoxESP(new BlockPos(a), new Color(255, 255, 0), false, new Color(255, 255, 0), 1.0f, false, true, 42, true);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 1)) {
                this.surroundRender(a, -1.0, 0.0, 0.0, true);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 2)) {
                this.surroundRender(a, 1.0, 0.0, 0.0, true);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 3)) {
                this.surroundRender(a, 0.0, 0.0, -1.0, true);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 4)) {
                this.surroundRender(a, 0.0, 0.0, 1.0, true);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 5)) {
                this.surroundRender(a, -1.0, 0.0, 0.0, false);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 6)) {
                this.surroundRender(a, 1.0, 0.0, 0.0, false);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 7)) {
                this.surroundRender(a, 0.0, 0.0, -1.0, false);
            }
            if (EntityUtil.getSurroundWeakness(a, -1, 8)) {
                this.surroundRender(a, 0.0, 0.0, 1.0, false);
            }
        }
    }

    private void surroundRender(Vec3d pos, double x, double y, double z, boolean red) {
        BlockPos position = new BlockPos(pos).func_177963_a(x, y, z);
        if (SurroundRender.mc.field_71441_e.func_180495_p(position).func_177230_c() == Blocks.field_150350_a || SurroundRender.mc.field_71441_e.func_180495_p(position).func_177230_c() == Blocks.field_150480_ab) {
            return;
        }
        if (red) {
            RenderUtil.drawBoxESP(position, new Color(255, 0, 0), false, new Color(255, 0, 0), 1.0f, false, true, 42, true);
        } else {
            RenderUtil.drawBoxESP(position, new Color(0, 0, 255), false, new Color(0, 0, 255), 1.0f, false, true, 42, true);
        }
    }

    private EntityPlayer getTarget(double range) {
        EntityPlayer target = null;
        double distance = range;
        for (EntityPlayer player : SurroundRender.mc.field_71441_e.field_73010_i) {
            if (EntityUtil.isntValid(player, range) || !EntityUtil.isInHole(player)) continue;
            if (target == null) {
                target = player;
                distance = SurroundRender.mc.field_71439_g.func_70068_e(player);
                continue;
            }
            if (!(SurroundRender.mc.field_71439_g.func_70068_e(player) < distance)) continue;
            target = player;
            distance = SurroundRender.mc.field_71439_g.func_70068_e(player);
        }
        return target;
    }
}

**Comment by cheroso1337** [comment]
No

**Comment by Random3131** [comment]
No

**Comment by JOniGod** [comment]
the guys dont like cityesp?

**Comment by Random3131** [comment]
> the guys dont like cityesp?

Useless module + it looks bad

**Comment by JOniGod** [comment]
ok my bad suggestion i dont know how to del this suggestion

**Comment by Random3131** [comment]
Just close it

**Comment by Zane2b2t** [comment]
are you blind
