### ISSUE TITLE
[FEATURE] Add civbreak

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#217]

**Comment by 3arthqu4ke** [comment]
Duplicate of #102 also Megyn added Speedmine Instant and CrystalBomber I am just not sure how well they work.

**Comment by master7720** [comment]
> Duplicate of #102 also Megyn added Speedmine Instant and CrystalBomber I am just not sure how well they work.

cev and civ are both different things

**Comment by 3arthqu4ke** [comment]
Enlighten me, no description has been provided.
