### ISSUE TITLE
[FEATURE] Add CooldownBypass setting back and AutoCrystal version with all the old settings.

### ISSUE THREAD

**Issue by autocrystal** [3arthqu4ke/3arthh4ck#218]
**Is your feature request related to a problem? Please describe.**
Why was the CooldownBypass removed from the AutoCrystal? It made the ca faster on some servers. 

**Describe the solution you'd like**
Add back the CooldownBypass setting for AutoCrystal. Or maybe even add add "AutoCrystalDev" with all the good settings.

**Describe alternatives you've considered**
The only alternative is to not eat gapples or have a slower ca. I would like to eat and have a fast ca at the same time.

**Additional context**
no, I can send video of it being slower if you dont understand.

**Comment by Random3131** [comment]
there is cooldown bypass option in switch?

**Comment by Random3131** [comment]
and autocrystal is same nothing's changed

**Comment by autocrystal** [comment]
He have changed it and remove almost all settings.

**Comment by autocrystal** [comment]
Use the latest build and you will see

**Comment by Random3131** [comment]
> He have changed it and remove almost all settings.

no??

**Comment by Random3131** [comment]
> Use the latest build and you will see

go to settings module in client section and then change complexity to expert

**Comment by autocrystal** [comment]
I see, thanks
