### ISSUE TITLE
[FEATURE]Autocrystal Better Extrap: Player move Y calculation

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#221]
In the predictions (Extrap) of many clients in 2020-2022, I have experienced a lot of different predictions. I found that if the prediction can be made to not calculate the fall of the player after jumping when the player continues to move, but continue to calculate forward ( Because the player is continuously moving forward) will make the predict effect better
![P%62MUMV_1)2DOU7NU})5U5](https://user-images.githubusercontent.com/92873946/188301722-53120c2e-968d-4bb0-aab5-4da03227b26a.png)
The green predict line is: Calculation of Y drop when no player moves
white line: 3arthh4ck
earthhack-autocrystal-Extrap will calculate the Y when the player falls. This calculation is not smooth. If you can make the extrap fall during the player's movement without calculation or reduce the calculation deviation, it will make the crystal pair more accurate and cause more damage to the enemy. multiple injuries

**Comment by Random3131** [comment]
damn

**Comment by 3arthqu4ke** [comment]
Uh not sure if I understand this correctly but you think calculating falling is bad? Have you tried turning down the Extra-Gravity setting?

**Comment by 3arthqu4ke** [comment]
Or do you want an option to just calculate movement in x/z direction?

**Comment by JOniGod** [comment]
Yes, but only -Y is not calculated, the Y of height is still calculated

**Comment by 3arthqu4ke** [comment]
Cant you achieve this by setting Extra-Gravity to zero? I can make some other settings tho, sure

**Comment by JOniGod** [comment]
I tried getting Extra-Gravity off, but it didn't do what I wanted

**Comment by Zane2b2t** [comment]
Wow

**Comment by 3arthqu4ke** [comment]
Can you tell me what this https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2988352614 does for you? There is a setting called Y-Minus-Factor which allows you to control how much the fall-y gets taken into account. Y-Plus-Factor is the same but for upwards motion.

**Comment by JOniGod** [comment]
Very good, the experience of cpvp has been improved again, and the effect is the same as what I want, thank you(btw  Don't forget to fix the fade->damgerender issue) :P

**Comment by JOniGod** [comment]
![{@`PEJ}20@G@GQ%X)EQ}MUD](https://user-images.githubusercontent.com/92873946/188320070-669c6b0d-234a-43f2-bce9-377e84edadc7.png)
the predict good now

**Comment by 3arthqu4ke** [comment]
> Very good, the experience of cpvp has been improved again, and the effect is the same as what I want, thank you(btw Don't forget to fix the fade->damgerender issue) :P

-_- yes I will see what I can do
