### ISSUE TITLE
[FEATURE] OnGround speed setting

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#223]
**Is your feature request related to a problem? Please describe.**
For the speed module, mode OnGround there isn't a speed modifier/timer modifier, so it lags back (not entirely)

**Describe the solution you'd like**
Add the ability to set the speed of OnGround mode

**Additional context**
Maybe even adding the ability to use more modes? Like if I press the bind, the strafe mode turns off and the other on (idk, do what you want, I will just use an other client for the other speed mode)

**Comment by 3arthqu4ke** [comment]
> **Additional context** Maybe even adding the ability to use more modes? Like if I press the bind, the strafe mode turns off and the other on (idk, do what you want, I will just use an other client for the other speed mode)

There is a macro here that does something like that
https://github.com/3arthqu4ke/3arthh4ck/blob/c949bf816979c1511706803c2b66a9029c52f1db/configs/macros/ongroundconfig.json

**Comment by Ai2473** [comment]
> There is a macro here that does something like that https://github.com/3arthqu4ke/3arthh4ck/blob/c949bf816979c1511706803c2b66a9029c52f1db/configs/macros/ongroundconfig.json

Nice, I didn't think about making a macro thx

**Comment by 3arthqu4ke** [comment]
Best I can do is the Speed - Modify with Speed - XZ - Modifier
