### ISSUE TITLE
[FEATURE] No render

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#226]
+add remove particles (fireworks, explosion, block break, eating, critical,...)
+add remove scoreboard, potion overlay
+ remove black background 
from this
![image](https://user-images.githubusercontent.com/97225256/188359648-9b311f07-2714-4964-a50e-8ec4e9862483.png)
to this
![image](https://user-images.githubusercontent.com/97225256/188359657-102999e4-7322-4ca9-b2d7-cce6f1829baf.png)

**Comment by JOniGod** [comment]
remove particles can be turned off in optfine's particle effects
Image 2 can be achieved with only texture packs

**Comment by 3arthqu4ke** [comment]
Yeah, just use Optifine, basically there is no reason not to use it

**Comment by GurteX** [comment]
you can turn off any particles but not block breaking 🧐

**Comment by peef609** [comment]
> remove particles can be turned off in optfine's particle effects Image 2 can be achieved with only texture packs

how can i do that
can you send me an example pack
