### ISSUE TITLE
[BUG]Auto armor 

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#228]
**Describe the bug**  
turn on auto mend, earthhack won't auto mend even the % of armor is lower than the setting
also no take off armor.
**To Reproduce**  
1. Turn on autoarmor
2. Set the armor percent to 30%, then make the armor be 29%
3. Turn on Exp tweaks with silent switch with middle click
4. See the error, no put of armor

**Comment by GurteX** [comment]
goofy ahh

**Comment by 3arthqu4ke** [comment]
Have you tried actually holding down MiddleClick?

**Comment by peef609** [comment]
> Have you tried actually holding down MiddleClick?

yes, I used stacks of exp

**Comment by peef609** [comment]
> > Have you tried actually holding down MiddleClick?
> 
> yes, I used stacks of exp

sorry my fault
