### ISSUE TITLE
[FEATURE]Chorus Predict

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#229]
Add chorus predict
Describe: when u eat chorus, it will render the place u will teleport to before you accept it
to accept, make a bind for it. Then you will be teleported as soon as u accept it.
If not, eat another one to choose another place to teleport.
Render mode: Box+tracers.

**recommend add mouse for the bind**

**Comment by 3arthqu4ke** [comment]
Can be done using AntiPackets - SPlayerPosLook + LagoMeter/Sounds just turn AntiPackets off once you want to teleport.

**Comment by peef609** [comment]
> Can be done using AntiPackets - SPlayerPosLook + LagoMeter/Sounds just turn AntiPackets off once you want to teleport.

seems complicated qwq

**Comment by GurteX** [comment]
🤨

**Comment by Ozynt** [comment]
Add predict render for other players as well. This means you can see where people with choruscontrol will teleport. 
Like this but with an esp box instead. 
https://user-images.githubusercontent.com/58683893/152617331-784ac17a-924e-4a09-83f9-2ebed60b036e.mp4
