### ISSUE TITLE
[FEATURE] NoRender [Updated]

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#230]
+add remove block break particle
+add remove potion icons
![image](https://user-images.githubusercontent.com/97225256/188372821-a4609507-12ab-434a-80fc-4f3e322807fd.png)

**Comment by 3arthqu4ke** [comment]
> +add remove block break particle

What do you mean the cracks?

> add remove potion icons

HUD -> Potions Hide or Text

**Comment by Zane2b2t** [comment]
Already a thing

**Comment by Zane2b2t** [comment]
> > > +add remove block break particle
> > 
> > 
> > What do you mean the cracks?
> > > add remove potion icons
> > 
> > 
> > HUD -> Potions Hide or Text
> 
> no i mean the particles when u break a block, it appears as tiny seeds

Already a thing i think? Turn all particles off in optifine

**Comment by ta-o666** [comment]
no optifine can't remove block breaking particles

**Comment by ta-o666** [comment]
> > > > +add remove block break particle
> > > 
> > > 
> > > What do you mean the cracks?
> > > > add remove potion icons
> > > 
> > > 
> > > HUD -> Potions Hide or Text
> > 
> > 
> > no i mean the particles when u break a block, it appears as tiny seeds
> 
> Already a thing i think? Turn all particles off in optifine

optifine can't remove block breaking particles
