### ISSUE TITLE
[BUG] Blur & CostumFont conflicting with CatEars

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#232]
**Describe the bug**  
In the gui turning on blur & cat ears with costum font makes cat ears have black background instead of transparent 

**To Reproduce**  
1. Turn on cat ears
2. Enable blur (in gui)
3. Turn on costum font

**Additional context**  
Not a biggie but it triggers me lol

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by mdo992** [comment]
> I have included logs
did you?

very good solution: dont use clickgui catears

**Comment by mdo992** [comment]
> also it also says "or steps to reproduce the issue." which i provided

error logs/stack traces always help and makes it easier for the developer

**Comment by Zane2b2t** [comment]
> 

i mean... he can easily replicate the bug himself + it'll be better
