### ISSUE TITLE
[FEATURE] autoswitch in offhand

### ISSUE THREAD

**Issue by GentlemanMC** [3arthqu4ke/3arthh4ck#234]
**Is your feature request related to a problem? Please describe.**
i want to switch to a crystal in my offhand without pressing the bind lol
**Describe the solution you'd like**
make a setting to autoswitch when there is no lethal crystal/ when your health is above the safety health setting
**Describe alternatives you've considered**
future offhand lol

**Comment by 3arthqu4ke** [comment]
So basically make it that crystal is the default mode?

AutoCrystal can make Offhand AutoSwitch but you probably use Future AC?

**Comment by Zane2b2t** [comment]
> Make a modeSetting, for changing the offhand mode. For this: https://github.com/3arthqu4ke/3arthh4ck/blob/main/src/main/java/me/earth/earthhack/impl/modules/combat/offhand/modes/OffhandMode.java I can make a pr if you want.

yesyes i want i keep having to press the offhand bind

just with mode it'll be alot easier

**Comment by 3arthqu4ke** [comment]
> > So basically make it that crystal is the default mode?
> > AutoCrystal can make Offhand AutoSwitch but you probably use Future AC?
> 
> yes and only switches to the totem when there is a lethal crystal or when your health has reached the safeHealth value then switches back when your health goes back up

For the switch back, have you tried RecoverySwitch?

**Comment by GentlemanMC** [comment]
yes...

**Comment by GentlemanMC** [comment]
sorry for opening this i dumb, recoverswitch does what i want
but
pls add a setting for swordgap to work when im holding crystals

**Comment by 3arthqu4ke** [comment]
Will do in #212
