### ISSUE TITLE
[BUG] Speedmine BreakCrystal issue

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#235]
https://user-images.githubusercontent.com/103523147/188643868-e9d4d7fe-3530-483a-998b-01fba04bd245.mp4

BreakCrystal in Speedmine only breaks crystal which are placed next to obsidian and not on the obsidian

**Comment by 3arthqu4ke** [comment]
😅 I know it is a bit confusing but breakCrystal only breaks crystals that are already there. The crystals Speedmine places itself need to be broken with AutoCrystal ahhhhhhhhhhhhhhhhhhhhh. I guess this could be done better...

**Comment by Random3131** [comment]
Yea, if u could make speedmine break crystals which it places it could be broken a lil bit faster ig

**Comment by Zane2b2t** [comment]
i lick yuo config :+1:
