### ISSUE TITLE
[FEATURE] wireframe holeesp

### ISSUE THREAD

**Issue by eghGFEu9hifbehf** [3arthqu4ke/3arthh4ck#236]
option to add a wireframe cross inside the holeesp
example: https://imgur.com/a/U7PeakB

**Comment by Zane2b2t** [comment]
i dislike this.

**Comment by xyzbtw** [comment]
look ugly ngl, it would only look nice if it was a pyramid going up with those lines

**Comment by Zane2b2t** [comment]
> look ugly ngl, it would only look nice if it was a pyramid going up or down with those lines

shut up chinease client fan

**Comment by peef609** [comment]
> look ugly ngl, it would only look nice if it was a pyramid going up or down with those lines

hi moloch.su user

**Comment by xyzbtw** [comment]
> > look ugly ngl, it would only look nice if it was a pyramid going up or down with those lines
> 
> hi moloch.su user

I have access to it but I don't use it, just saying on how it would look better

**Comment by TerikKek** [comment]
it looks clean lol what are yall saying
