### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#238]
[latest.log](https://github.com/3arthqu4ke/3arthh4ck/files/9509188/latest.log)
I'm guessing it's something to related to config from what I see in the log idk?
was working just fine until I force closed the pc and came back 30 mins later to see it crashing
(this is 1.8.3 from actions but also crashed in latest release)

**Comment by Zane2b2t** [comment]
I can prob fix this by copying earthhack folder and then deleting it
booting up earthhack and if it loaded I'll put the earthhack folder back in

**Comment by Zane2b2t** [comment]
it worked lol im so fucking smart (real)
lemme try put back og earthhack folder and see if it crashes again

**Comment by Zane2b2t** [comment]
ok it doesnt work with the og folder idk
i really need this folder
[earthhack.zip](https://github.com/3arthqu4ke/3arthh4ck/files/9509235/earthhack.zip)

**Comment by 3arthqu4ke** [comment]
u might have to backup your configs every few days because earthhacks config system is the worst shit ever. but cant fix cause too much work. ur config corrupted :(

**Comment by 3arthqu4ke** [comment]
It looks like its just the WoodzCC.json in modules

**Comment by 3arthqu4ke** [comment]
Try to delete that one

**Comment by 3arthqu4ke** [comment]
Did you change a StringSetting with a weird value by any chance?

**Comment by 3arthqu4ke** [comment]
Configs.json is corrupted too idk why

**Comment by 3arthqu4ke** [comment]
Also heres a plugin that backs up your earthhack directory when you run the game https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3011000053

Maybe u tried to create a config with a weird name?

**Comment by Zane2b2t** [comment]
> Also heres a plugin that backs up your earthhack directory when you run the game https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3011000053
> 
> Maybe u tried to create a config with a weird name?

No

I made a new folder and transferred binds and the 3 comfigs i use instead of it being bloated and it worked

**Comment by Zane2b2t** [comment]
> It looks like its just the WoodzCC.json in modules

I'll see i haven't touched that config for a while
