### ISSUE TITLE
[BUG]offhand viewmodel doesnt work at all 

### ISSUE THREAD

**Issue by hentaienjoy3r** [3arthqu4ke/3arthh4ck#24]

**Comment by 3arthqu4ke** [comment]
Can't recreate, do you use other mods/clients?

**Comment by GentlemanMC** [comment]
u can recreate the issue by loading future with it (compatibility issue)

**Comment by GentlemanMC** [comment]
(again)

**Comment by 3arthqu4ke** [comment]
Doesn't future have a SmallShield/Viewmodel module? If they have a similar module which you could use instead I don't really want to fix this.

**Comment by Sandwich4780** [comment]
> Doesn't future have a SmallShield/Viewmodel module? If they have a similar module which you could use instead I don't really want to fix this.

Yeah future has a viewmodel.

**Comment by 3arthqu4ke** [comment]
So use that then I'd say
