### ISSUE TITLE
[FEATURE] Extend Surround by walking against a block

### ISSUE THREAD

**Issue by 3arthqu4ke** [3arthqu4ke/3arthh4ck#240]
Basically trigger the AntiTrap - Fill mode by walking against a block until a threshold is reached. We could count the time we are collidedHorizontally + have a movement bind pressed.

**Comment by Zane2b2t** [comment]
so addicted to developing that he dreams about stuff to make in his bed

**Comment by 3arthqu4ke** [comment]
How did you know??? Send help 🆘

**Comment by Zane2b2t** [comment]
> 

i can relate to this lol happens alot

**Comment by Random3131** [comment]
> Basically trigger the AntiTrap - Fill mode by walking against a block until a threshold is reached. We could count the time we are collidedHorizontally + have a movement bind pressed.

or probably make surround extend if it detects if someone is phasing in our surround

**Comment by 3arthqu4ke** [comment]
> > Basically trigger the AntiTrap - Fill mode by walking against a block until a threshold is reached. We could count the time we are collidedHorizontally + have a movement bind pressed.
> 
> or probably make surround extend if it detects someone phasing in our surround

It already does that with PlayerExtend, I think. This is mostly to prevent bomber crystals placed against your surround.

**Comment by 3arthqu4ke** [comment]
For now this can be done by PacketFlying a bit into a block with Extend on. Not sure if good enough.
