### ISSUE TITLE
[FEATURE] AntiTrap - AntiBomb

### ISSUE THREAD

**Issue by 3arthqu4ke** [3arthqu4ke/3arthh4ck#241]
- [x] Places two blocks above us, maybe also on the blocks for AntiFacePlace + 1y? 
- [ ] Similar to #240 an option that extends this when jumping against the head block? (nahh lets not do this)
- [x] Similar to #240 an option that breaks crystals on the head block when jumping (can be done with Attack)

**Comment by Random3131** [comment]
![phobo](https://user-images.githubusercontent.com/103523147/189408048-63946c2b-f33c-49f6-90fe-d22760e923de.jpg)

**Comment by Zane2b2t** [comment]
> ![phobo](https://user-images.githubusercontent.com/103523147/189408048-63946c2b-f33c-49f6-90fe-d22760e923dnice meme u got there, im gonna need that meme, i'll steal it and there's nothing u could do about it
