### ISSUE TITLE
i feel like the ca is a lil bit worse idk

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#243]

**Comment by 3arthqu4ke** [comment]
PseudoDead and DeathTime settings got a bugfix, you might wanna check that. You can turn down deathtime a lot if it multiplaces i think or something, idk, try my eucc config.

**Comment by 3arthqu4ke** [comment]
Also some evidence, video etc. would be nice.

**Comment by Zane2b2t** [comment]
> 

I tried your eucc config placement is good, I'll also check the psuedodead and deathtime setting idk where r they but I'll look

**Comment by Zane2b2t** [comment]
> PseudoDead and DeathTime settings got a bugfix, you might wanna check that. You can turn down deathtime a lot if it multiplaces i think or something, idk, try my eucc config.

cant find these settings can u tell me where are they?

also i can't record my laptop is dogshit lol

**Comment by 3arthqu4ke** [comment]
On the SetDead page

**Comment by Zane2b2t** [comment]
> On the SetDead page

fixed but that makes me notice another issue

when psuedeath is on my crystals dont render when autocrystal is on

**Comment by Zane2b2t** [comment]
also while we're in this closed issue can u tell me how to install custom shaders? i copied another client's shader file opened glslbox pasted code from glsl to the file i got from other client posted it in shader files and it didnt work idk
