### ISSUE TITLE
[BUG] AutoCrystal Faceplace Issue

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#244]
https://user-images.githubusercontent.com/103523147/189304228-8f63e07f-718a-4b46-a7f3-17a9506cbf84.mp4

Faceplace places far when you are using HoldFacePlace

**Comment by 3arthqu4ke** [comment]
It tries to minimize self damage. You can probably configure it in a way so it does not.

**Comment by Random3131** [comment]
tried changing many stuff, it still didn't stop doing that

**Comment by 3arthqu4ke** [comment]
You are also in creative, go into survival.

**Comment by Random3131** [comment]
Same thing in survival

**Comment by 3arthqu4ke** [comment]
Try changing SelfFactor on the Development page if you use UseSafetyFactor.

**Comment by Random3131** [comment]
i dont use safety factor, here's the config tho
https://pastebin.com/3kJa4U0T

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3021825359 try this, either turn down CompareDiff or turn on FacePlaceCompare.

**Comment by Random3131** [comment]
yea, its good now thanks
