### ISSUE TITLE
[BUG] Killaura doesn't work while riding a horse.

### ISSUE THREAD

**Issue by VitorISs** [3arthqu4ke/3arthh4ck#248]
If I'm riding a horse with Killaura active and get close enough to a mob, the module does not hit the entity even though it should.

1. Hop on a horse.
2. Activate Killaura (with the monsters option selected).
3. Get close enough to a mob (under the Killaura range, 4.1 in my case).
4. Killaura does nothing (does not hit the mob).

I'm pretty sure that Killaura should work even if riding entities, so you wouldn't need to dismount in order to kill certain mobs.

As you can see in this screenshot, i'm close enough to the target (spider, 1.82 blocks away) but the module isn't hitting it.
![Screenshot_2](https://user-images.githubusercontent.com/30983029/189465521-7a997cd0-4884-4022-8f4f-9b0eba7abace.png)

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
Are you using other clients, like future?

**Comment by 3arthqu4ke** [comment]
Closing this issue, it is inactive and I can not recreate it.
