### ISSUE TITLE
Lock issue or something to do with that.

### ISSUE THREAD

**Issue by owowowowowo-png** [3arthqu4ke/3arthh4ck#25]
I don't really know how to explain it. A video will hopefully make you understand .
https://streamable.com/pqlki7

I tried without earthhack and just future client and everything was fine. no lock issue. but when I use earthhack (even with no modules on) still I have this issue. I checked if I was using any future modules as well if that was breaking it. I disabled every modules on both clients and still got this issue.

**Comment by hentaienjoy3r** [comment]
i have that issue when im using gs

**Comment by cPyrobyte** [comment]
Its not phobos issue but future this happends when im using phobos and future

**Comment by Sandwich4780** [comment]
Are you using the compatibility module?

**Comment by owowowowowo-png** [comment]
> Are you using the compatibility module?

no??

**Comment by Sandwich4780** [comment]
> > Are you using the compatibility module?
> 
> no??

Try using it, it should fix the issue.

**Comment by owowowowowo-png** [comment]
> > > Are you using the compatibility module?
> > 
> > 
> > no??
> 
> Try using it, it should fix the issue.

Alright,
