### ISSUE TITLE
[BUG] Surround doesn't switch to the correct block.

### ISSUE THREAD

**Issue by VitorISs** [3arthqu4ke/3arthh4ck#250]
**Describe the bug** 

Whenever i activate Surround, the module tries to place blocks around me but it doesn't switch to the obsidian on my hotbar (not even silently) and the timer on the arraylist stays locked at 0.0 as if it was constantly trying to place the blocks but couldn't.
It only places the blocks if i manually select them on my hotbar (while the module is activated), but, if before getting to the obsidian i select any other blocks or placeable/usable thing, it uses/places it instead of the obsidian (as you can see by the screenshots, it placed 4 signs around when holding signs and it also constantly llights the floor around me on fire when i'm holding a flint and steel, wasting its durability), it also doesn't replace the blocks surrounding me if one of the blocks get removed (unless i select the obsidian). It behaves as if i was constantly right clicking the 4 blocks around me all the time with whatever i'm holding.

![isqueiro](https://user-images.githubusercontent.com/30983029/189466904-beeb345c-98eb-42ab-90d8-df991cdec763.png)
![placas](https://user-images.githubusercontent.com/30983029/189466907-76e51dbc-8ca9-4571-982e-eed7e14af5b2.png)
![surround3](https://user-images.githubusercontent.com/30983029/189466911-b3c9f520-722d-4e6e-b35d-669b1dd9b7a2.png)

**To Reproduce**  
1. Activate Surround.
2. Stand still (nothing should happen if you're not holding any placeable items)
3. Manually select the Obsidian/Flint and Steel/Signs/etc.
4. Now it gets placed. Even if it's not the obsidian that the player originally wanted to.

**Expected behavior**  
I believe that the expected behavior is that when you activate the module it instantly surrounds you in obsidian (and also replaces it if it gets removed by someone) without you having to manually select it. And it also shouldn't use any other items except maybe ender chests if the player would want to.

**Additional context**  
It could actually just be some setting incorrectly configured or a module compatibility issue, but I've checked all the settings and modules active at the same time and couldn't find a solution or why that was happening.
These are the settings i'm currently using (even though i've already changed it a lot but couldn't get to a solution)

![surround4](https://user-images.githubusercontent.com/30983029/189466981-040f56f4-51e4-4733-8fdb-c1e5778de290.png)
![surround5](https://user-images.githubusercontent.com/30983029/189466983-ce4c06c5-321e-434b-a520-22a113b70a93.png)
![surround6](https://user-images.githubusercontent.com/30983029/189466984-2a94a32a-15a2-4bda-a982-0fc24b64bfb0.png)

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
Are you using another client? Also try another Cooldowb-Bypass, e.g  None.

**Comment by Random3131** [comment]
Turn off cooldown bypass ig

**Comment by Zane2b2t** [comment]
That's a feature. fire protects you from bad people :pray:

**Comment by VitorISs** [comment]
> Are you using another client? Also try another Cooldown-Bypass, e.g None.

I'm using it with Lambda, but i'm not really using anything but it's render modules or modules that wouldn't influence that.
And looks like changing the Bypass-Cooldown to None solved the problem!

**Comment by 3arthqu4ke** [comment]
Which servers does this issue occur on? They might have patched it. It should not happen in singleplayer.

**Comment by 3arthqu4ke** [comment]
Closing this issue, it is inactive and I can not recreate it. It might happen on servers that have patched it, in that case turn it off.

**Comment by Zane2b2t** [comment]
> 

i have accidently recreated this in singleplayer before  and when i had surround on  i was lagging

me and this guy prob had AntiPackets for item switching idk or maybe cooldown bypass it doesn't really matter anyways

**Comment by VitorISs** [comment]
> Which servers does this issue occur on? They might have patched it. It should not happen in singleplayer.

Sorry, didn't see your message. That happened on 9b9t and 5b5t, but i think it would still happen in all servers even tho i didn't try it. And i don't know about that antipackets thing the guy above said, but changing the cooldown-bypass to none solved my problem.
