### ISSUE TITLE
automine calculation [Do better damage]-[FEATURE]

### ISSUE THREAD

**Issue by AlexanderJonny** [3arthqu4ke/3arthh4ck#252]
FEATURE: 
![I3YZH{QBI_%X %J){P78$UO](https://user-images.githubusercontent.com/92873946/189499406-68056872-1790-4910-88d5-565314cd9907.png)
let automine stay for a while
![2GY73N($511A5}ISU3FNU 5](https://user-images.githubusercontent.com/92873946/189499475-8059ab67-cb22-4313-b4f1-46d3ace4a766.png)
Automine's calculation mechanism will calculate a new position after the block breaks, which makes the enemy unable to pop/kill. If you can let Automine stay in a position where high dmg can be played for a period of time to let the enemy pop/kill, this will undoubtedly enhance the practicality of Automine

Watch this maybe help : https://youtu.be/LJCut4dQ3pw

My idea: let automine stay for a while after calculating the high dmg position until the enemy calculates the new position after using AntiCity/AntiTrap(fill), instead of calculating the new position immediately after the block is broken

**Comment by Zane2b2t** [comment]
I suggest u remove automije completly
Shit robotic module only robots use

**Comment by JOniGod** [comment]
did u mean automine is robot module？
so autocrystal allows you to place crystals automatically, isn't that the same?

**Comment by Random3131** [comment]
> FEATURE: ![I3YZH{QBI_%X %J){P78$UO](https://user-images.githubusercontent.com/92873946/189499406-68056872-1790-4910-88d5-565314cd9907.png) let automine stay for a while ![2GY73N($511A5}ISU3FNU 5](https://user-images.githubusercontent.com/92873946/189499475-8059ab67-cb22-4313-b4f1-46d3ace4a766.png) Automine's calculation mechanism will calculate a new position after the block breaks, which makes the enemy unable to pop/kill. If you can let Automine stay in a position where high dmg can be played for a period of time to let the enemy pop/kill, this will undoubtedly enhance the practicality of Automine
> 
> Watch this maybe help : https://youtu.be/LJCut4dQ3pw
> 
> My idea: let automine stay for a while after calculating the high dmg position until the enemy calculates the new position after using AntiCity/AntiTrap(fill), instead of calculating the new position immediately after the block is broken

use speedmine mode fast (without using automine)

**Comment by BebSxy** [comment]
sick

**Comment by GRIFFiin** [comment]
> did u mean automine is robot module？ so autocrystal allows you to place crystals automatically, isn't that the same?

Don't argue with him, he's retarded

**Comment by 3arthqu4ke** [comment]
I will see what I can do. But you can also turn up the Reset-Offset a bit (like 150) with BlackList-For set to 0. With Reset-Offset it will wait and check if the player surrounds again.

**Comment by JOniGod** [comment]
watch this https://youtu.be/puvtQ8ia7Pc
I did as you said, but the effect doesn't seem to change

**Comment by 3arthqu4ke** [comment]
Can you turn off Improve? Its kinda bad. Improve-Invalid is ok.

**Comment by AlexanderJonny** [comment]
I tried it, but still the same effect as in the video
https://youtu.be/4VT2OC3TXwU

**Comment by 3arthqu4ke** [comment]
Hmm, I also use a delay of 100, does that help?

**Comment by AlexanderJonny** [comment]
It didn't help, I set the delay to 100, and the same effect still appeared.

**Comment by AlexanderJonny** [comment]
watch this video the other client automine : https://youtu.be/KU8V5DaE_nM
The effect tested in the single-player game is not complete，You may be able to watch and refer to this video.

src.

// Decompiled with: Procyon 0.6.0
// Class Version: 8
package me.alpha432.stay.features.modules.combat;

import java.util.Iterator;
import net.minecraft.entity.Entity;
import me.alpha432.stay.util.world.BlockUtil;
import net.minecraft.init.Blocks;
import me.alpha432.stay.features.modules.misc.InstantMine;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;
import me.alpha432.stay.util.world.EntityUtils;
import me.alpha432.stay.util.inventory.InventoryUtil;
import net.minecraft.init.Items;
import java.util.Objects;
import me.alpha432.stay.manager.ModuleManager;
import net.minecraft.entity.player.EntityPlayer;
import me.alpha432.stay.features.setting.Setting;
import me.alpha432.stay.features.modules.Module;

public class AutoCity extends Module
{
    private final Setting<Boolean> disable;
    public EntityPlayer target;
    
    public AutoCity() {
        super("AutoCity", "AutoCity", Category.COMBAT, false, false, false);
        this.disable = this.register(new Setting<Boolean>("AutoDisable", true));
    }
    
    @Override
    public void onTick() {
        if (fullNullCheck()) {
            return;
        }
        if (Objects.requireNonNull(ModuleManager.getModuleByName("AutoCev")).isEnabled()) {
            return;
        }
        if (this.disable.getValue()) {
            this.disable();
        }
        if (InventoryUtil.getItemHotbar(Items.field_151046_w) == -1) {
            return;
        }
        this.target = this.getTarget(6.0);
        this.surroundMine();
    }
    
    @Override
    public String getDisplayInfo() {
        if (this.target == null) {
            return null;
        }
        return this.target.func_70005_c_();
    }
    
    private void surroundMine() {
        if (this.target == null) {
            return;
        }
        final Vec3d a = this.target.func_174791_d();
        if (EntityUtils.getSurroundWeakness(a, 1, -1)) {
            this.surroundMine(a, -1.0, 0.0, 0.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 2, -1)) {
            this.surroundMine(a, 1.0, 0.0, 0.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 3, -1)) {
            this.surroundMine(a, 0.0, 0.0, -1.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 4, -1)) {
            this.surroundMine(a, 0.0, 0.0, 1.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 5, -1)) {
            this.surroundMine(a, -1.0, 0.0, 0.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 6, -1)) {
            this.surroundMine(a, 1.0, 0.0, 0.0);
            return;
        }
        if (EntityUtils.getSurroundWeakness(a, 7, -1)) {
            this.surroundMine(a, 0.0, 0.0, -1.0);
            return;
        }
        if (!EntityUtils.getSurroundWeakness(a, 8, -1)) {
            return;
        }
        this.surroundMine(a, 0.0, 0.0, 1.0);
    }
    
    private void surroundMine(final Vec3d pos, final double x, final double y, final double z) {
        final BlockPos position = new BlockPos(pos).func_177963_a(x, y, z);
        if (InstantMine.getInstance().isOff()) {
            InstantMine.getInstance().enable();
            return;
        }
        if (!InstantMine.getInstance().isOn()) {
            return;
        }
        if (InstantMine.breakPos != null) {
            if (InstantMine.breakPos.equals(position)) {
                return;
            }
            if (InstantMine.breakPos.equals(new BlockPos(this.target.field_70165_t, this.target.field_70163_u, this.target.field_70161_v)) && AutoCity.mc.field_71441_e.func_180495_p(new BlockPos(this.target.field_70165_t, this.target.field_70163_u, this.target.field_70161_v)).func_177230_c() != Blocks.field_150350_a) {
                return;
            }
        }
        AutoCity.mc.field_71442_b.func_180512_c(position, BlockUtil.getRayTraceFacing(position));
    }
    
    private EntityPlayer getTarget(final double range) {
        EntityPlayer target = null;
        double distance = range;
        for (final EntityPlayer player : AutoCity.mc.field_71441_e.field_73010_i) {
            if (!EntityUtils.isntValid(player, range)) {
                if (!EntityUtils.isInHole(player)) {
                    continue;
                }
                if (target == null) {
                    target = player;
                    distance = AutoCity.mc.field_71439_g.func_70068_e(player);
                }
                else {
                    if (AutoCity.mc.field_71439_g.func_70068_e(player) >= distance) {
                        continue;
                    }
                    target = player;
                    distance = AutoCity.mc.field_71439_g.func_70068_e(player);
                }
            }
        }
        return target;
    }
}

**Comment by 3arthqu4ke** [comment]
Just so we understand each other. You are talking about Mode Fast right? Smart cant keep a block mined like Mode Fast and this will not really matter as Mode Smart always needs the same time to break a block.

**Comment by AlexanderJonny** [comment]
The mode I use is instant. My suggestion is: when using speedmine:instant and automine, automine will dig blocks, but it will quickly switch targets. After automine switches to a new position, the enemy's surrounding has been repositioned. Ok, obsidian, this can't do the best damage, I want you to add a function to automine, the function of this function is: use automine when using speedmine (instant), let automine add a calculation after the mining block is dropped Delay when other blocks.
I tried setting the automine-delay's delay to 3000, and it did what I wanted, but after I did that, the enemy entered my automine and the block was calculated after delay: 3000, if you understand me I mean, plzzz, be sure to add this feature!

**Comment by Random3131** [comment]
so do you mean to add a feature that keep mining the same block instead switching to other surrounding blocks?

**Comment by AlexanderJonny** [comment]
Yeah, that's what it means
edit: I don't understand English, I've been using a translator, so I'm not sure you guys understand what I mean

**Comment by 3arthqu4ke** [comment]
No no this has bothered me before too, Im working on it

**Comment by AlexanderJonny** [comment]
I think a better solution is to divide the delay of Automine into two, namely the delay when the player enters the calculation range of Automine, and the delay when Automine calculates other positions.

**Comment by 3arthqu4ke** [comment]
Tell me what this https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3129409058 does for you. The setting is MultiBreakCheck and is already on.

**Comment by AlexanderJonny** [comment]
How does he work? , I don't seem to have any change after using it, it still has the same effect as in the video above.
my config
![HAZ34_CO0WS{@{NVOGL DLY](https://user-images.githubusercontent.com/92873946/192335529-502d5888-9ff7-4188-a68b-1354f64b5f73.png)
![XR}2IK9A1Y){{OSDU7$ZL_8](https://user-images.githubusercontent.com/92873946/192335545-dc7cf87b-9d1d-4299-874a-64f1322a137c.png)

**Comment by 3arthqu4ke** [comment]
Yes something is broken, will fix tomorrow.

**Comment by 3arthqu4ke** [comment]
Tell me if this: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3135831993 helps. Also turn on SpeedmineCrystalDamageCheck which will use the MinDamage configured in Speedmine, so make sure that MinDamage in Speedmine and in Automine are the same.

**Comment by AlexanderJonny** [comment]
Although the fix was successful, a new problem ensued
watch：https://youtu.be/9dveVXspfDo
automine successfully stays in place after the calculation, but if the location where the crystal can be placed is blocked, automine will not calculate the new location

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/actions uhhhh turn on DependOnSMCheck but its not perfect yet

**Comment by AlexanderJonny** [comment]
I think there are still things that need to be fixed
watch this:https://youtu.be/kkQoOrUczYs
If there is a square above speedmine, it will keep digging repeatedly.

**Comment by 3arthqu4ke** [comment]
What about this: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3160430386

**Comment by AlexanderJonny** [comment]
very good It's really awesome! Thank you so much for making this feature for me!
I will pray to God and bless you ! Amen.

**Comment by 3arthqu4ke** [comment]
You are welcome!
