### ISSUE TITLE
[BUG] HUD duplicates some modules 

### ISSUE THREAD

**Issue by master7720** [3arthqu4ke/3arthh4ck#255]
![2022-09-10_20 33 33](https://user-images.githubusercontent.com/80098736/189511293-2cfafa0a-5ae7-42a5-a932-01145907df17.png)

**Comment by Zane2b2t** [comment]
turn off all modules in pb-gui :brain:

**Comment by Random3131** [comment]
goofy ahh issue

**Comment by master7720** [comment]
> turn off all modules in pb-gui 🧠

they are

**Comment by GentlemanMC** [comment]
> turn off all modules in pb-gui 🧠

inane

**Comment by 3arthqu4ke** [comment]
Cant recreate, can you send a config + pb-config where I can recreate this issue? Are you using the old HUD plugin?
