### ISSUE TITLE
Speed in gui

### ISSUE THREAD

**Issue by BebSxy** [3arthqu4ke/3arthh4ck#256]
add speed, in the gui, that modifies the speed with which the gui is raised and lowered

**Comment by pon44561** [comment]
what speed?

**Comment by Zane2b2t** [comment]
> add speed, in the gui, that modifies the speed with which the gui is raised and lowered

There isnt even animations to begin with and it should stay that way

**Comment by BebSxy** [comment]
> > add speed, in the gui, that modifies the speed with which the gui is raised and lowered
> 
> There isnt even animations to begin with and it should stay that way

retard u dont understand
