### ISSUE TITLE
add spin to popchams

### ISSUE THREAD

**Issue by BebSxy** [3arthqu4ke/3arthh4ck#257]
llololollo that would look sick

**Comment by BebSxy** [comment]
spin left and right and spinspeed

**Comment by BebSxy** [comment]
oh and spin mode

**Comment by BebSxy** [comment]
Spin: min -10.0 max 10.0 default 0.0
SpinSpeed: min 0.0, max 10.0, default 0.0
lol

**Comment by BebSxy** [comment]
@cattyngmd

**Comment by GRIFFiin** [comment]
Add death cham but the cham fly up to the sky with a fade effect

**Comment by 3arthqu4ke** [comment]
Hows that supposed to look? Which direction should they spin in?

**Comment by BebSxy** [comment]
https://youtu.be/LGtWYdJiZYM?t=78
