### ISSUE TITLE
[FEATURE] shrink render option for autocrystal

### ISSUE THREAD

**Issue by Woodz2706** [3arthqu4ke/3arthh4ck#259]
shrink render option for autocrystal, opposite of expand, would render whenever the ca is done rendering, as seen in https://github.com/Luna5ama/TrollHack

**Comment by GentlemanMC** [comment]
> shrink render option for autocrystal, opposite of expand, would render whenever the ca is done rendering, as seen in https://github.com/Luna5ama/TrollHack

bruh stop suggesting stuff from a kamiblue skid

**Comment by Woodz2706** [comment]
> > shrink render option for autocrystal, opposite of expand, would render whenever the ca is done rendering, as seen in https://github.com/Luna5ama/TrollHack
> 
> bruh stop suggesting stuff from a kamiblue skid

the expand and slide render options are literally pasted from trollhack

**Comment by 3arthqu4ke** [comment]
There is a Zoom setting.

**Comment by BebSxy** [comment]
nice iq

**Comment by Zane2b2t** [comment]
> shrink render option for autocrystal, opposite of expand, would render whenever the ca is done rendering, as seen in https://github.com/Luna5ama/TrollHack

i already recommended this and i think u can make ca render shrink by changing the Zoom offset

**Comment by Zane2b2t** [comment]
> > shrink render option for autocrystal, opposite of expand, would render whenever the ca is done rendering, as seen in https://github.com/Luna5ama/TrollHack
> 
> bruh stop suggesting stuff from a kamiblue skid

technically xiarooo worked on kamiblue and lambda so technicaly it isn't a skid
also trollhack isnt a mad skid like 99% of skids there's 10x more changes than lambda
