### ISSUE TITLE
[FEATURE] Add web bypass

### ISSUE THREAD

**Issue by cow167** [3arthqu4ke/3arthh4ck#263]
mode cancel
mode block
mode motion (differents  from vhspeed and vspeed in noslowdown)

**Comment by 3arthqu4ke** [comment]
I have no clue how these Modes are supposed to work. Please provide more information. How is NoSlowDown not good enough?

**Comment by cow167** [comment]
> I have no clue how these Modes are supposed to work. Please provide more information. How is NoSlowDown not good enough?

yeah, the web bypass actually need to improve more
