### ISSUE TITLE
[FEATURE] Add Blocker

### ISSUE THREAD

**Issue by cow167** [3arthqu4ke/3arthh4ck#268]
Describe: place obsidian around to block pistonaura, cev and civ break

**Comment by GRIFFiin** [comment]
Selftrap. Don't thanks me

**Comment by cow167** [comment]
> Selftrap. Don't thanks me

what you gonna do with piston aura
don't thanks me

**Comment by 3arthqu4ke** [comment]
AntiTrap - Mode Faceplace
