### ISSUE TITLE
[FEATURE] Add obby bypass to PistonAura

### ISSUE THREAD

**Issue by GRIFFiin** [3arthqu4ke/3arthh4ck#269]
Will push a crystal IN a obby block that is on top of the target.
this type of bypass works on some servers.

Also bug : redstone torch is placed on top of the piston which doesn't activate it.

**Comment by 3arthqu4ke** [comment]
Can you send a clip?

**Comment by Zane2b2t** [comment]
> 

well i can't get a clip but i can give u good explaination

if the enemy is trapped and there's obi above him crystals pushed into the obi block above him can still deal damage,
