### ISSUE TITLE
[FEATURE] Installer...

### ISSUE THREAD

**Issue by BebSxy** [3arthqu4ke/3arthh4ck#270]
remove the installer, it doesn't work and no one uses it

**Comment by cow167** [comment]
agree

**Comment by Zane2b2t** [comment]
> BebSxy

idk if it works i tried it but never really opend minecraft lol
i agree that no one uses it tho.

**Comment by 3arthqu4ke** [comment]
It works and can be used to install 3arthh4ck into non-forge installations like standalone Optifine.

**Comment by BebSxy** [comment]
no work
