### ISSUE TITLE
[BUG] AutoCrystal Delayed when switching item in hotbars (mainhand)

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#272]
That's also for surround btw, when holding any item for example gapple and u switch back to crystal the CA will not start placing/calculating instantly making you miss out on some pops
idk if this is a bug or not but this also happens on singleplayer so its either a bug or config issue (which is unlikely cus i spent 2 days making my cfg)

Update: I fixed this by playing around with AntiPackets, idk which setting though so u may look and add descriptions into that
Another Update: it was **CHeldItemChange** which i belive cancels the packets that i switched items which then i realized causes surround and other shit to place what ever i was placing Ex. crystal etc.
You may use this information to fix switching delay for ca thingy and do anote attempt to **SilentSwitch Bypass**

**Comment by 3arthqu4ke** [comment]
Cooldown/Place-Cooldown?

**Comment by Zane2b2t** [comment]
> Cooldown/Place-Cooldown?

My cool down is at 1 and tbh ive never seen the setting place cool down will double check

**Comment by 3arthqu4ke** [comment]
config issue. can not recreate!
