### ISSUE TITLE
[FEATURE] Strict option for LongJump & packetmine

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#273]
for packetmine idk how will this work but for longjump it will attempt to bypass the anticheat (for example 2b2tpvp's) by jumping when taking damage that deals KnockBack
the current LongJump works on 2bpvp however its not the best
1 day later me: also add **AutoJump** option for it so it jumps when turning on longjump even if you don't move, it'll only go up not forwards, that may make LongJump rubberband less.

future me finally putting this on GH: make AutoOff setting on longjump turn off longjump when you completed the jump instead of when you lag

**Comment by Random3131** [comment]
Wdym by strict option for packet mine?

**Comment by Zane2b2t** [comment]
> 

Like cosmos
A mode

**Comment by Random3131** [comment]
What does it exactly do?

**Comment by Zane2b2t** [comment]
> 

i said idk about packetmine lol it just works ig

**Comment by Random3131** [comment]
Pretty sure 3arthh4ck's speedmine works on 2bpvp If u just turn on rotate

**Comment by Zane2b2t** [comment]
> Pretty sure 3arthh4ck's speedmine works on 2bpvp If u just turn on rotate

Strict 2bpvp and 2bpvp anticheat is ass bro
Packetmine don't work on 2b like on strict 2bpvp
