### ISSUE TITLE
[FEATURE] Costum X & Z settings for CA extrap

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#274]
just like Y+ and Y- but for XZ, it should make extrap better and smarter
also add Y+z Y-Z Y+X Y-X settings since sometimes i see in the extrap render the Y extraps just sometimes go all the way down/up (even when player is moving forward/backwards and upwards/downwards)
this should fix it by extrap moving better diagonaly

**Comment by 3arthqu4ke** [comment]
I might add a horizontal XZ-Factor, thats it.

**Comment by Zane2b2t** [comment]
> 

👍

**Comment by Zane2b2t** [comment]
> 

also if you could bring back old 1.0.0 ca (it had AutoCrystal and CrystalAura) that'd be cool, or maybe as a plugin bcs tbh the current ca is bloated and for cc you dont need all of this bloat i feel its making ca less effective
