### ISSUE TITLE
[FEATURE] Move WireFrame Chams into a separate module

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#276]
it makes more sense + will give people more space, also there's modes option for ESP but there's only 1 mode so move wireframe to that!
will give more costumizablity and shit
also add diffrent modes for diffrent entitys, for players i want outline and for items i want box but it just shows text which i dont like

**Comment by 3arthqu4ke** [comment]
I would rather have a third module.
> also add diffrent modes for diffrent entitys, for players i want outline and for items i want box but it just shows text which i dont like

Stuff like this should be a separate issue imo.
