### ISSUE TITLE
[BUG] CopyAnimation in popchams not including body (just the body) rotations 

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#279]
in this clip popchams should copy exactly the player but body and it's joints (hands legs etc.) copies as if the body is straight which it isn't

no clip cope im sure 99% of the people know what i mean if u request a clip/screenshot tell me

**Comment by 3arthqu4ke** [comment]
clip.

**Comment by Zane2b2t** [comment]
> 

👍
