### ISSUE TITLE
[FEATURE] phobos-1.0.0 GUI plugin

### ISSUE THREAD

**Issue by icpvpbadly** [3arthqu4ke/3arthh4ck#28]
**Is your feature request related to a problem? Please describe.**
i use a different resolution and the normal gui is oversized, so i need to click on the phobosGUI module everytime i enter the clickgui and its getting annoying

**Describe the solution you'd like**
make it so that i can disable/enable the phobosGUI plugin module anytime i want

**Comment by GurteX** [comment]
just bind the phobosGUI module lol

**Comment by 3arthqu4ke** [comment]
I don't support the old plugins rn, sorry. Especially not the phobos-gui plugin as it was thrown together quickly.
