### ISSUE TITLE
[FEATURE] Diffrent calcs and settings (for ca) if you..

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#281]
i think that having some settings changed for diffrent healthes in ca would be nice and unique
phobos ca is known to have the most amount of setting and i belive this setting could help on some situitations
Also PLEASE add descriptions for BowKiller settings

**Comment by Random3131** [comment]
You could try override place and break

**Comment by Zane2b2t** [comment]
> You could try override place and break

i made another issue about override place where it just keeps multiplacing while calculating a pos without reaching maxselfplace value which sucks
also its not costumizeable

**Comment by Sandwich4780** [comment]
ok zane2b2t
