### ISSUE TITLE
[FEATURE] Spectator check into anchor

### ISSUE THREAD

**Issue by xyzbtw** [3arthqu4ke/3arthh4ck#286]
Spectator check into anchor so it doesn't try to pull you into a hole while you are spectating

**Comment by Zane2b2t** [comment]
> Spectator check into anchor so it doesn't try to pull you into a hole while you are spectating

Wow that tottaly breaks the game making you lose it all

**Comment by xyzbtw** [comment]
> > Spectator check into anchor so it doesn't try to pull you into a hole while you are spectating
> 
> Wow that tottaly breaks the game making you lose it all

Is it not useful? People opened an issue about a spectator check in killaura, and either cattyn or earthquake fixed it

**Comment by xyzbtw** [comment]
Thanks!
