### ISSUE TITLE
[BUG]Image chams not working again + No CrystalChams image mode

### ISSUE THREAD

**Issue by Nutelaspaceman** [3arthqu4ke/3arthh4ck#287]
So idk if you fixed it or smng and the issue is only for me
but when I use either custom shader or image mode, it doesnt work
maybe custom shader needs a .frag or something else than a png but image mode still doesn't work.
Also it can't load images in the earthhack minecraft directory
Also you closed my crystalchams image mode as "completed" but there are no crystalchams with image mode

https://user-images.githubusercontent.com/79189729/191799368-4eca4fdb-b011-4bde-9afe-b1ab55a72ff4.mp4

![Screenshot_878](https://user-images.githubusercontent.com/79189729/191799557-574da289-48da-4cee-a204-dcf42e9d8990.png)

**Comment by Zane2b2t** [comment]
I get the same thing i was lazy to make an issue

**Comment by Zane2b2t** [comment]
> I get the same thing i was lazy to make an issue

(But for shader files not images

**Comment by 3arthqu4ke** [comment]
Custom Shader needs a frag file with [this](https://github.com/3arthqu4ke/3arthh4ck/blob/main/src/main/resources/shaders/water.shader) format. 

I have not touched Image shader, I do not think it ever worked.

**Comment by Zane2b2t** [comment]
> 

my shader files are already in frag format i yoinked them from another client lol
windows just denies phobos from accessing this folder i guess??

**Comment by Nutelaspaceman** [comment]
> > 
> 
> my shader files are already in frag format i yoinked them from another client lol windows just denies phobos from accessing this folder i guess??

add it to another folder, also send me them shaders 😻

**Comment by Nutelaspaceman** [comment]
> Custom Shader needs a frag file with [this](https://github.com/3arthqu4ke/3arthh4ck/blob/main/src/main/resources/shaders/water.shader) format.
> 
> I have not touched Image shader, I do not think it ever worked.

It can't access my downloads folder
