### ISSUE TITLE
[FEATURE] Jesus on rideable entities

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#288]
**Describe the solution you'd like**
Ability to use jesus with rideable entities

**Describe alternatives you've considered**
Ngl flying pigs would be cool to have

**Additional context**
entityspeedhack with jesus too?

**Comment by 3arthqu4ke** [comment]
Can you tell me if this https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3113605671 works for you. I havent tested it on actual servers yet

**Comment by Ai2473** [comment]
Ok so, it works on singleplayer

And it works on servers, but you unmount if you try to get back on ground (?) https://streamable.com/yadje9
