### ISSUE TITLE
[FEATURE] Rewrite BedAura

### ISSUE THREAD

**Issue by cathusiast** [3arthqu4ke/3arthh4ck#295]
**Is your feature request related to a problem? Please describe.**
Current BedAura is a quick port from old phobos

**Describe the solution you'd like**
Rewrite module entirely (also add Bed item to Offhand)

**Additional context**
https://www.youtube.com/watch?v=hztFjFovFEw

**Comment by Zane2b2t** [comment]
Beds were only used on old 5b and 1.13+ servers i dont really see a use for bed aura rn
