### ISSUE TITLE
[BUG] Freecam not loading chunks/blocks

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#297]
**Describe the bug**  
Freecam doesn't load the chunks/blocks as intended
![2022-09-24_10 57 03](https://user-images.githubusercontent.com/102620545/192089568-9f024854-795b-496d-9a61-960be428ab5e.png)

**To Reproduce**  
1. Turn on freecam
2. Go underground
3. Play around with the Y axis to see something

**Expected behavior**  
A clear underground view

**Additional context**  
It was in the older versions too (1.3.1; 1.6.2...)

**Comment by Zane2b2t** [comment]
Dont think thats a bug

**Comment by Ai2473** [comment]
> Dont think thats a bug

💀
