### ISSUE TITLE
Know issues

### ISSUE THREAD

**Issue by 1OOO1O** [3arthqu4ke/3arthh4ck#3]
Here is a few issues I would like to be fixed.
• CrystalChams not working
• Chams on Future not working when using earthhack (atleast not crystal chams)
~~• In gopro336’s version there were rainbow timestamps. Please add it back.~~ done

Also ty for making fixes for earthhack ❤️

**Comment by 3arthqu4ke** [comment]
Most rendering modules have been made by megyn and I don't have future so I'll have to see how to approach this. Doesn't Future have CrystalChams too which you could use instead? When it comes to rendering modules I would always use futures over ours because theirs have priority on some things. I'll take a look at the timestamps idk why they would be missing.

**Comment by 1OOO1O** [comment]
Ty for rainbow timestamps fix, I would use Future crystal chams but something maybe is messing with the priority for Future crystal chams.

**Comment by Lolwut22** [comment]
you can go impl/core/mixins/render/entity/MixinRenderEnderCrystal and delete the "/*" on both sides of if (CHAMS.isEnabled()) {
and delete the folder "model" under impl/core/mixins/render/model

**Comment by Lolwut22** [comment]
and make sure to delete the class from mixins.earth.json

**Comment by nossravgni** [comment]
Also the rpc doenst work at all

**Comment by 1OOO1O** [comment]
> Also the rpc doesn't work at all

The code is completely fine, it's just that the discord rpc application is not active anymore.

**Comment by 15360enes** [comment]
crystalchams is in the client its just quoted so it doesnt work

**Comment by 3arthqu4ke** [comment]
I unquoted CrystalChams and it seemed p broken, I'll see if I can restore how they were at some point.

**Comment by 3arthqu4ke** [comment]
CrystalChams and Chams should be compatible now and the RPC should be fixed. You can find a jar [here](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2178000035). Will close this tomorrow unless someone finds something.

**Comment by 3arthqu4ke** [comment]
Apart from this maybe causing #18 I don't see any issues.
