### ISSUE TITLE
[FEATURE]Animations Module

### ISSUE THREAD

**Issue by alimustafa53tr** [3arthqu4ke/3arthh4ck#30]
I think you get the thing but i can explain it

in minecraft when you switch between items the item slowly appears with a delay animations module disables ( like 1.7) that and also lets you customize the swinging speed

**Comment by GurteX** [comment]
sounds good but,

**Comment by Zane2b2t** [comment]
Cool idea

**Comment by alimustafa53tr** [comment]
@3arthqu4ke  are you interesting in making this? or should i close the issue

**Comment by GurteX** [comment]
> @3arthqu4ke are you interesting in making this? or should i close the issue

close ur mouth
