### ISSUE TITLE
[FEATURE] Added SuperBow

### ISSUE THREAD

**Issue by TikyMan** [3arthqu4ke/3arthh4ck#305]
SuperBow a combat module
Damage For Bow from 1 to 100

**Comment by TikyMan** [comment]
how use what teleports

**Comment by TikyMan** [comment]
Ok Added In BowKiller Damage From 1 To 100

**Comment by Zane2b2t** [comment]
> Ok Added In BowKiller Damage From 1 To 100

Thats not how it works pal, even if it does it would only work on singleplayer

**Comment by shasdfasdqw** [comment]
> 

this is not how it works, the faster the arrow goes, the more damage it does to the player bowkiller has been patched on most servers and bow killer you have to wait a long time for one shot op detected warns you to tighten it but this time can be reduced by setting bow spam
