### ISSUE TITLE
[question] hud editor

### ISSUE THREAD

**Issue by 15360enes** [3arthqu4ke/3arthh4ck#31]
Are you interested in working on hud editor?

**Comment by Sandwich4780** [comment]
I believe hud editor works if you bind it, close the clickgui and then press the hud editor bind you set (this might be wrong as I haven’t tried it).

**Comment by GentlemanMC** [comment]
> I believe hud editor works if you bind it, close the clickgui and then press the hud editor bind you set (this might be wrong as I haven’t tried it).

its not wrong
the hudeditor works fine u just need to bind it and close the gui then press the keybind
u also need to set "hud->mode->both" for the elements to be visible

**Comment by linkvy** [comment]
i dont think you can turn on the hud components, at least ive tried turning them on and the buttons are broken

**Comment by GentlemanMC** [comment]
u can

**Comment by 3arthqu4ke** [comment]
not interested will be gone soon >:D
