### ISSUE TITLE
[FEATURE] SuperKnokback

### ISSUE THREAD

**Issue by TikyMan** [3arthqu4ke/3arthh4ck#313]
the player flies much further away

**Comment by shasdfasdqw** [comment]
stop suggesting nonsense modules anymore i think this is impossible
and it's not a 1.8 hvh client

**Comment by GRIFFiin** [comment]
this aint fdp client

**Comment by CascadeDemon** [comment]
yall less spam report that nigga lel

**Comment by Random3131** [comment]
> the player flies much further away

U can use speed with velocity mode on or long jump with velocity mode on

**Comment by VitorISs** [comment]
i remember seeing this in a 1.8 client and it worked, with a single hit the player took like double the knockback, but it was like 5 years ago AND in 1.8, it should be patched by now OR just doesn't work in 1.9+ i guess

**Comment by 3arthqu4ke** [comment]
This could probably be done in a similar way bowkiller is done, I might add it as a feature to criticals but it is kinda useless.

**Comment by 3arthqu4ke** [comment]
nvm it wont
