### ISSUE TITLE
[FEATURE] Individual block editor for Search.

### ISSUE THREAD

**Issue by VitorISs** [3arthqu4ke/3arthh4ck#315]
**Is your feature request related to a problem? Please describe.**

I think the way Search works right now is a bit "basic", as it only displays the same color for every block you're searching for, which isn't ideal as players would not notice something they're looking for thinking it was just another thing that pops up more frequently in the tracers (like not noticing something like a placed beacon thinking it was a spawner, as both have the same esp/tracer color and shape).

**Describe the solution you'd like**

So adding a better module editor with more customization would make it much better. It could work like this: A button in the module settings called Editor, that when you click it, it'd display a little window with a list of the blocks you are searching for, and if you click on them, a color picker would pop up and allow you to change the color of the tracers and esp for that specific block (like purple for nether portals, blue for spawners, red for beds, rainbow for shulker boxes, white for diamond blocks, etc).

**Additional context**

That's considered essential for players that hunt for bases/stashes/etc and usually have a lot of things on Search, as the only real way to judge what popped up on search is, is the amount of blocks side by side (like a 3x2 portal or a double chest/bed) which isn't optimal.

**Comment by xyzbtw** [comment]
So you want it to be like impact (the only client that has it like that)

**Comment by VitorISs** [comment]
> So you want it to be like impact (the only client that has it like that)

No, it's not the only one (I think impact doesn't even have that?).
But yeah not a lot of clients have that, and it sure is a very positive differential to the ones that have it.

**Comment by Zane2b2t** [comment]
+search add/del <block> bruh

**Comment by VitorISs** [comment]
> +search add/del bruh

the "issue" has nothing to do with that
