### ISSUE TITLE
[FEATURE] Add Tunnel ESP.

### ISSUE THREAD

**Issue by VitorISs** [3arthqu4ke/3arthh4ck#316]
Tunnel ESP is a module that highlights tunnels that were probably dug by players. It would search for 1x2, 1x1, 1x3, 2x2, etc tunnels in your render distance and highlight them through walls.

This is very useful when searching for stuff in the nether as people tend to dig a lot of tunnels to their destinations. And also in the overworld so you can notice that there was player activity there.

An option to set a limit would also be useful so players with weaker pcs don't lag when a lot of tunnels pop up.

**Comment by cow167** [comment]
@3arthqu4ke good first issue
