### ISSUE TITLE
[BUG] Pingbypass connection to server (6b6t) fails

### ISSUE THREAD

**Issue by HAV0X1014** [3arthqu4ke/3arthh4ck#319]
When using Pingbypass to connect to 6b6t on release 1.8.4 (and below), instead of connecting successfully, it will fail connection.

The server setup is with 3arth 1.8.4, HeadlessMC 1.5.2, HeadlessForge 1.2.0, HMC-Specifics-1.12.2-b2, no 3arth plugins.

The jvmargs i'm using are -Xmx1700M -Dheadlessforge.no.console=true

The connection attempt to 6b6t.org begins after line 1747
[latest.log](https://github.com/3arthqu4ke/3arthh4ck/files/9659305/latest.log)

This was run on an ubuntu 22.04 VM and ubuntu 20.04 VPS with the same results.

**Comment by Zane2b2t** [comment]
> When using Pingbypass to connect to 6b6t on release 1.8.4 (and below), instead of connecting successfully, it will fail connection.
> 
> The server setup is with 3arth 1.8.4, HeadlessMC 1.5.2, HeadlessForge 1.2.0, HMC-Specifics-1.12.2-b2, no 3arth plugins.
> 
> The jvmargs i'm using are -Xmx1700M -Dheadlessforge.no.console=true
> 
> The connection attempt to 6b6t.org begins after line 1747 [latest.log](https://github.com/3arthqu4ke/3arthh4ck/files/9659305/latest.log)
> 
> This was run on an ubuntu 22.04 VM and ubuntu 20.04 VPS with the same results.

if it doesn't work on 6b then it prob doesnt work on 8b


maybe bcs cracked servers with passwords idk?

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3138779034 can you try this version?

**Comment by HAV0X1014** [comment]
Works perfectly now using that version. No extra changes were needed.
Tested on VPS and VM.
