### ISSUE TITLE
[BUG] holetp doesnt work / [Feature] Anchor

### ISSUE THREAD

**Issue by Nope0xAL4TAC** [3arthqu4ke/3arthh4ck#32]
like it does absolutely nothing, doesnt even work on nonstrict servers

**Comment by Ozynt** [comment]
It does work it's just not made for servers with anti-cheat. Try it out in singleplayer and you will see.

**Comment by lifeofacookie** [comment]
who doesnt hack in single player

**Comment by Zane2b2t** [comment]
Newgen 7b/2y2c mains don't have rights to talk

**Comment by ZenovJB** [comment]
> Newgen 7b/2y2c mains don't have rights to talk

u have 2b2t in ur name incel

**Comment by lifeofacookie** [comment]
Don’t mess with zane he plays 1.12 German skywars

**Comment by Nope0xAL4TAC** [comment]
LOL SINGEPLAYER HACK
3arthqu4ke u can close it now

**Comment by Nope0xAL4TAC** [comment]
> newgen 7b/2y players dont have rights to tlak

LOL STFU
