### ISSUE TITLE
guide for YouTube or Russian translate?

### ISSUE THREAD

**Issue by xXKINGofPEPEXx** [3arthqu4ke/3arthh4ck#320]
a guide for each function with a more detailed description or a video guide.  it is possible to translate the description in the cheat into Russian?

![IMG_20220928_012346](https://user-images.githubusercontent.com/66877688/192648958-504523f3-8c4a-4c49-8f66-ee46150d1716.jpg)

**Comment by CascadeDemon** [comment]
poshel nahui eblan

**Comment by TikyMan** [comment]
Чел ты...

**Comment by CascadeDemon** [comment]
> Чел ты...

haha why am i not surpised that ur siberian XDDDD

**Comment by xyzbtw** [comment]
Just learn english, it's not hard

**Comment by GRIFFiin** [comment]
More retarded module for hypixel servers

**Comment by TikyMan** [comment]
Impact Client Modules

**Comment by cmetanamaker** [comment]
nahuy eng coderam ebatsa s drugimi yazikami?

**Comment by TikyMan** [comment]
xz
