### ISSUE TITLE
[FEATURE] Make AutoArmor change sets depending on the damage you're getting

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#322]
if you're getting sword damage make it REPLACE (not un-equip and equipping)the set you're wearing with protection 4 armor 
blah blah and for blast damage blah blah

**Comment by xyzbtw** [comment]
hm, weren't you the one talking shit about robotic modules?

**Comment by Zane2b2t** [comment]
> 

how is that robotic

it isnt game changer or anything
if you think being robotic is not using modules at all then lets play vanilla!!!!

**Comment by GRIFFiin** [comment]
> > 
> 
> how is that robotic
> 
> it isnt game changer or anything if you think being robotic is not using modules at all then lets play vanilla!!!!

You're actually brain dead

**Comment by GRIFFiin** [comment]
> hm, weren't you the one talking shit about robotic modules?

Uhhh so this guy has "2b2t" in his name do don't expect high iq from him

**Comment by Zane2b2t** [comment]
> > hm, weren't you the one talking shit about robotic modules?
> 
> Uhhh so this guy has "2b2t" in his name do don't expect high iq from him

I agree having 2b2t in the name is retarded the name "ZANE" is just not available and I don't want my name to be "XxZANE69xX"

also who tf r u and how is my suggestion robotic

**Comment by 3arthqu4ke** [comment]
You can do it with a macro. I think its a bit of a bad idea, if you get crystalbombed with prot you pop instantly.

**Comment by Zane2b2t** [comment]
> 

oh tbh haven't thought about crystal bombing
