### ISSUE TITLE
[BUG] SpeedMine BreakCrystal Issue

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#327]
https://user-images.githubusercontent.com/103523147/193411959-9e03c9ea-7660-47ea-a2e0-9a91c781d4b0.mp4

it seems like it is not able to break crystals it is spawning??? but can break existing crystals

cfg-https://pastebin.com/gwJxPn7Z

**Comment by CRTCTY** [comment]
Which server is that on?

**Comment by CRTCTY** [comment]
Which server is that on?

**Comment by Random3131** [comment]
> Which server is that on?

cc

**Comment by CRTCTY** [comment]
I had this too, but CrystalAura fixes it. Make it so that I dont need CrystalAura

**Comment by Random3131** [comment]
> I had this too, but CrystalAura fixes it. Make it so that I dont need CrystalAura

Kinda fixes it but it would be alot faster if speedmine breaks the spawning crystal insted of ac

**Comment by Zane2b2t** [comment]
maybe u need ca on!!! but then break crystal is basically useless idk

**Comment by Random3131** [comment]
Nah i don't think u need ca to break them. The break crystal module can break pre existing crystal and tries to attack the spawning one but it can't break it
