### ISSUE TITLE
[BUG] Bugs

### ISSUE THREAD

**Issue by GurteX** [3arthqu4ke/3arthh4ck#33]
- **HoleTP**: worst shit desyncs and doesnt work
- **ReChams**: remove cuz its impossible to make them work normally
- **AutoCrystal**: multiplace calculations (?)
- **Chams**: [FireShader] doesnt work for me unlike WaterShader and GalaxyShader
- **Waypoints**: works actually bad for me ( even range is 8172482832 (?) )
-----------------------------------------------------------------------------------------
and missing descriptions.

**Comment by Sandwich4780** [comment]
Rechams work for me just fine????

**Comment by Zane2b2t** [comment]
Rechams work.

**Comment by Nope0xAL4TAC** [comment]
> Rechams work.

stfu they dont

**Comment by Zane2b2t** [comment]
Bro nop0 you're a 2y2c/8b main 2022 who literally asked for newbase configs in comments 🤡 💀

**Comment by 3arthqu4ke** [comment]
>    * **AutoCrystal**: multiplace calculations (?)

(?)


>    * **Waypoints**: works actually bad for me ( even range is 8172482832 (?) )

please elaborate

There's a bug and a feature template, please follow those and provide information which allows me to understand what this means.

**Comment by GurteX** [comment]
> > * **AutoCrystal**: multiplace calculations (?)
> 
> (?)
> 
> > * **Waypoints**: works actually bad for me ( even range is 8172482832 (?) )
> 
> please elaborate
> 
> There's a bug and a feature template, please follow those and provide information which allows me to understand what this means.

nope there are no feature template
