### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by queenellee** [3arthqu4ke/3arthh4ck#330]
Konas Client and 3arthh4ck aren't compatiable

**To Reproduce**  
1. Go to 'mods folder and put Konas and 3arthh4ck in it.'
2. Click on 'Play in the minecraft launcher and the wait'
3. See error (It crashes)

**Expected behavior**  
A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in. 

**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you! 

**Additional context**  

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

[latest.txt](https://github.com/3arthqu4ke/3arthh4ck/files/9748413/latest.txt)

**Comment by CascadeDemon** [comment]
thats intended

**Comment by Zane2b2t** [comment]
> thats intended

Chad

**Comment by GRIFFiin** [comment]
Simple fix : remove konas

**Comment by mdo992** [comment]
i should make a pr that fully breaks konas + earthhack compatibility
