### ISSUE TITLE
[BUG] SwordGapCrystal kick 

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#334]
https://user-images.githubusercontent.com/103523147/196449988-5ad45cc7-4b56-496a-babb-8a717d3d89a4.mp4

you get kicked if u use ca with swordgapcrystal
only happens when you use swordgapcrystal and not when you are only using  swordgapple

**Comment by Zane2b2t** [comment]
server issue + user issue

**Comment by GRIFFiin** [comment]
Config issue

**Comment by shxrkyylol** [comment]
@Random3131 how did u get the god bless 3arthh4ck this at the top of ur screen?>

**Comment by shxrkyylol** [comment]
> I dont think it is an config issue, I tried almost everything i can and this only happens on cc probably because of their silent switch patch

bro howd u get the god bless earthhack at the top ur screen

**Comment by Random3131** [comment]
By using phobos hud plugin

> @Random3131 how did u get the god bless 3arthh4ck this at the top of ur screen?>

By using phobos hud plugin

**Comment by shxrkyylol** [comment]
@Random3131 could you maybe send link to the hud mod please??

**Comment by Zane2b2t** [comment]
> @Random3131 could you maybe send link to the hud mod please??

https://github.com/3arthqu4ke/3arthh4ck/tree/plugins/hud

**Comment by nukiz** [comment]
Its a config issue, this happens when you're trying to place crystals and are eating with offhand at the same time.

**Comment by shxrkyylol** [comment]
> Its a config issue, this happens when you're trying to place crystals and are eating with offhand at the same time.

no, really??
