### ISSUE TITLE
[FEATURE] Add AntiChatLag

### ISSUE THREAD

**Issue by shxrkyylol** [3arthqu4ke/3arthh4ck#335]
**Is your feature request related to a problem? Please describe.**
I get mad when kids send thousands of unicode characters in chat or /whisper them to me, because it causes a crash, and I was wondering if it was possible to stop these messages or filter them out.

**Describe the solution you'd like**
I would like if there was a module that would filter these messages.

I've tried muting them, but the chat logs don't save, so I cant /ignore them.

**Additional context**
I dont have much else to say / give.

**Comment by CascadeDemon** [comment]
make it urself retard its likw 2.5 lines

**Comment by shxrkyylol** [comment]
@CascadeDemon bro ive never coded in java before
idk how it works

**Comment by CascadeDemon** [comment]
https://github.com/shxrkyylol/Calypso

use youtube Guides den lel

**Comment by shxrkyylol** [comment]
@CascadeDemon btw if its so easy make it urself

**Comment by CascadeDemon** [comment]
> @CascadeDemon btw if its so easy make it urself

???? i alr have that module degen lelz

**Comment by shxrkyylol** [comment]
> > @CascadeDemon btw if its so easy make it urself
> 
> ???? i alr have that module degen lelz

bro why u so mean? can u send it over please?

**Comment by mdo992** [comment]
if possible, put the error log and lag message on gist.github.com and i could make a pr adding it here https://github.com/3arthqu4ke/3arthh4ck/blob/main/src/main/java/me/earth/earthhack/impl/modules/misc/chat/Chat.java#L28

**Comment by shxrkyylol** [comment]
@mdo992 the message looks like this
![Screenshot 2022-10-29 173901](https://user-images.githubusercontent.com/100317628/198853374-83b4d9f4-9c0d-46e0-afd1-e806581d656a.png)

**Comment by shasdfasdqw** [comment]
There is a solution to this, of course, load the pop sound lag from the chat and you will crash once, then you will not live, but you have to do it when you leave the server and enter it all the time.

**Comment by shxrkyylol** [comment]
@shasdfasdqw could you try explaining it better? i am not understanding what the "pop sound lag" and when I "leave the server and enter it all the time"

**Comment by shasdfasdqw** [comment]
> @shasdfasdqw could you try explaining it better? i am not understanding what the "pop sound lag" and when I "leave the server and enter it all the time"

my english is bad when you enter or leave any server

**Comment by shasdfasdqw** [comment]
poplag crashes the game when a guy pops it sorry i said pop sound lag there will be pop lag 
in the chat section, pop lag will load, turn it on, it will crash for a moment.
