### ISSUE TITLE
CevBreaker, HeadCrystal

### ISSUE THREAD

**Issue by NotMer** [3arthqu4ke/3arthh4ck#336]
CevBreaker when or head crystal.

**Comment by GRIFFiin** [comment]
Its crystal bomber here

**Comment by shxrkyylol** [comment]
> CevBreaker when or head crystal.

my had a stroke while brain this reading that.

**Comment by shasdfasdqw** [comment]
just open auto trap and open automine crystals and open placecrystal from speedmine
