### ISSUE TITLE
[FEATURE] Inhibit

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#34]
Add inhibit so the crystal aura wont place another crystal before breaking the existing one it is helpful on strict servers

**Comment by Sandwich4780** [comment]
Doesn’t multiplace set to 1 do this?

**Comment by GurteX** [comment]
not multiplace, PseudoDead do this (probobaly)

**Comment by Random3131** [comment]
ok i will try it

**Comment by Random3131** [comment]
> Doesn’t multiplace set to 1 do this?

thanks it does just tried it
