### ISSUE TITLE
[BUG] Mouse Cursor

### ISSUE THREAD

**Issue by Diplomeunderscoore** [3arthqu4ke/3arthh4ck#340]
**Describe the bug**  
So if i open the client all is normal, but if i go into a world/server my Mouse cursor is always there.
If i open chat all is normal cuz the cursor is there but if i close its still there, i cant place of hit anything because of it
Anyone can help?

**Comment by shasdfasdqw** [comment]
There is a problem in its config, I knew the solution to it, I do not remember now, I will enter the game and write

**Comment by wagyswaggy** [comment]
> There is a problem in its config, I knew the solution to it, I do not remember now, I will enter the game and write

Thanks <3
