### ISSUE TITLE
[FEATURE] AutoWhisperUnicode

### ISSUE THREAD

**Issue by shxrkyylol** [3arthqu4ke/3arthh4ck#342]
**Is your feature request related to a problem? Please describe.**
This feature goes along with my AntiChatLag feature request. (https://github.com/3arthqu4ke/3arthh4ck/issues/335) But, I am always mad that I am fighting someone, and they whisper me tons of unicode which freezes my game, which then causes a freeze/lag making my AutoTotem fail.

**Describe the solution you'd like**
The client should note that when you pop someone, note the username, and automatically whisper them tons of junk unicode configurable via a .txt file in the 3arthh4ck/util folder.

**Describe alternatives you've considered**
Manually whispering the text, but that would also lag me out aswell.

**Additional context**
The message would look somewhat like this:

অআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌঅআইঈউঊঋঌ

**Comment by shxrkyylol** [comment]
![Screenshot 2022-10-29 173901](https://user-images.githubusercontent.com/100317628/198853356-5994ec91-75dc-4a72-96ae-6b45248a6b62.png)

**Comment by shxrkyylol** [comment]
that is what the message looks like

**Comment by shasdfasdqw** [comment]
I know that there is this, poplag in the chat section, when a player pops, he sends a pop message, but if we can spam when we want, the man's game can freeze a lot. but it makes sense

**Comment by shxrkyylol** [comment]
@shasdfasdqw, yes, I have just fould the pop lag, thank you!
