### ISSUE TITLE
[FEATURE] Selfhit

### ISSUE THREAD

**Issue by Munchax10** [3arthqu4ke/3arthh4ck#343]
**Is your feature request related to a problem? Please describe.**
On crystalpvp.cc, theres an pearl cooldown and it tries to patch pearl phasing. When changing the world, it bypasses the cooldown and allows you to phase easier.

**Describe the solution you'd like**
Add selfhit module to Misc category

**Describe alternatives you've considered**
Add it inside MCP as an option to selfhit before throwhing pearl.

**Additional context**
Just a module and when u click it, it hits urself 1 time. Could have settings with it spamming selfhit or setting a delay, but i can use the manual module toggling.

**Comment by shasdfasdqw** [comment]
In fact, it is not like this, you have to put the crystal and break it at the same time as you throw the pearl.
i don't know if it works with selfhit

**Comment by Munchax10** [comment]
> In fact, it is not like this, you have to put the crystal and break it at the same time as you throw the pearl. i don't know if it works with selfhit

It also works with placing obby and still holding obby and middle clicking pearl. Im not sure with swording or selfhitting but still, selfhit can be used for other purposes too.

**Comment by shasdfasdqw** [comment]
> > In fact, it is not like this, you have to put the crystal and break it at the same time as you throw the pearl. i don't know if it works with selfhit
> 
> It also works with placing obby and still holding obby and middle clicking pearl. Im not sure with swording or selfhitting but still, selfhit can be used for other purposes too.

you say right

**Comment by amendoa657** [comment]
this would also work to get out of double bedrock holes without blocks 🤔

**Comment by Munchax10** [comment]
> 

Yeah, moneymod has this feature but i would like it on 3arthh4ck

**Comment by Munchax10** [comment]
> > 
> 
> Yeah, moneymod has this feature but i would like it on 3arthh4ck

6b pvp has longjump but its buggy, when u take dmg it works again so im thinking of spamming selfhit while longjumpin. U can add a "delay" to do these things.
