### ISSUE TITLE
[SUGGESTION] Phobos 3.0.0 1.19

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#349]
Also thanks for existing without you this shithole would be way diffrent
It was nice having active community giving you suggestions and you implementing them while you was alive
You've left your mark forever

**Comment by GurteX** [comment]
Phobos 3.0.0 is already out.

**Comment by Zane2b2t** [comment]
> Phobos 3.0.0 is already out.

nice iq you got played
its not real YET.
