### ISSUE TITLE
[Hole-ESP Customisation ]

### ISSUE THREAD

**Issue by SirHilarious** [3arthqu4ke/3arthh4ck#359]
Please add the Option to Hole-ESP to just remove the Outline and have a simple full Box like in Phobos 1.9 or OyVey since it just looks good.

**Comment by 3arthqu4ke** [comment]
Cant you just turn the outline colors alpha to 0?

**Comment by cattyngmd** [comment]
no, theres no settings for outline colors iirc

**Comment by SirHilarious** [comment]
![2023-02-06_14 13 05](https://user-images.githubusercontent.com/97534927/216980871-b1c1811f-c527-49e3-a024-86b1ef9e360d.png)

Just checked and no there are none.
