### ISSUE TITLE
[BUG] Kit Command Crashing Future Still

### ISSUE THREAD

**Issue by unfidelity** [3arthqu4ke/3arthh4ck#36]
The .kit command still crashes future.

[latest.log](https://github.com/3arthqu4ke/3arthh4ck/files/8515974/latest.log)

**Comment by 3arthqu4ke** [comment]
Are you using the [latest](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2189554076) version? Can't recreate this.
