### ISSUE TITLE
strict rotations for servers like 2b2t

### ISSUE THREAD

**Issue by Arkloe** [3arthqu4ke/3arthh4ck#40]
add strciter rotations for 2b 😄

**Comment by 3arthqu4ke** [comment]
There's enough settings to make them slower or "stricter", I don't really get what you mean.

**Comment by Random3131** [comment]
> add strciter rotations for 2b 😄

pretty sure the current rotations work fine on 2b

**Comment by Arkloe** [comment]
3arth when  i tested phobos ca on 2b didnt work too well maybe it was my config i will test again
