### ISSUE TITLE
[BUG] Crashing on launch

### ISSUE THREAD

**Issue by Razerviper** [3arthqu4ke/3arthh4ck#42]
Minecraft crashes on launch with 3arthh4ck installed.
https://pastebin.ubuntu.com/p/n8JynTPccZ/
As you can see, I had some mods with 3arthh4ck installed, but even without them I got the same error.
I have future client installed. 
Using replay mod with this gives a different error, but it's not a big deal if there's an incompatibility between replay mod and 3arthh4ck, I just want this incompatibility between future and 3arth to be solved.
Using older versions, such as gopro's 1.3.1 version, does not crash minecraft.
Thank you for your help

**Comment by 3arthqu4ke** [comment]
MacOS is currently not supported, will be fixed once I move the ModelTotem module to a Plugin.

**Comment by Razerviper** [comment]
Thanks. I'll close this once it is

**Comment by 3arthqu4ke** [comment]
You could try [this](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2216984825) version.

**Comment by master7720** [comment]
> Minecraft crashes on launch with 3arthh4ck installed. https://pastebin.ubuntu.com/p/n8JynTPccZ/ As you can see, I had some mods with 3arthh4ck installed, but even without them I got the same error. I have future client installed. Using replay mod with this gives a different error, but it's not a big deal if there's an incompatibility between replay mod and 3arthh4ck, I just want this incompatibility between future and 3arth to be solved. Using older versions, such as gopro's 1.3.1 version, does not crash minecraft. Thank you for your help

heres a fix dont use macOS
