### ISSUE TITLE
[BUG] Offhand viewmodel and animations are broken

### ISSUE THREAD

**Issue by Nutelaspaceman** [3arthqu4ke/3arthh4ck#44]
**Offhand viewmodel and animations are broken**

try using offhand for place and break hand to check the animations
try moving offhand up and down using viewmodel

Clip: https://cdn.discordapp.com/attachments/966632403470794773/967393773753597962/offhand.mp4?size=4096

**Comment by lyricnight** [comment]
Happens when you use future with phobos, just use future smallshield and it will work
