### ISSUE TITLE
[FEATURE] Aspect

### ISSUE THREAD

**Issue by Nutelaspaceman** [3arthqu4ke/3arthh4ck#45]
**Aspect Module**

stretches resolution/game like cs:go

i think you know how it looks like but here is a ss:  ![Screenshot_460](https://user-images.githubusercontent.com/79189729/164947929-c14dfaaa-a9f7-45e4-8e6a-a17590a0abfe.png)

**Comment by NegroFighter69420** [comment]
this already exists, its in the management module

**Comment by ZenovJB** [comment]
> **Aspect Module**
> 
> stretches resolution/game like cs:go
> 
> i think you know how it looks like but here is a ss:  ![Screenshot_460](https://user-images.githubusercontent.com/79189729/164947929-c14dfaaa-a9f7-45e4-8e6a-a17590a0abfe.png)

nice brain
