### ISSUE TITLE
[FEATURE] Predict Offset/Ticks

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#46]
Since predict is already present in ca can u make it so that we can manually choose predict offset/ticks
eg:- https://streamable.com/yuerkc 2 tick/offset 
https://streamable.com/q177c6 10 tick/offset

**Comment by 3arthqu4ke** [comment]
Those settings are called Break/PlaceExtrapolation and are already in the client. While the description for those settings says "Not yet implemented." they actually are implemented... At least I think so. I would generally not use the Predict stuff tho.
