### ISSUE TITLE
Coding Help lol

### ISSUE THREAD

**Issue by ThnksCJ** [3arthqu4ke/3arthh4ck#47]
how tf do you do the -tweakclass thingy ive been looking at it for hours and have no clue how it works

**Comment by 3arthqu4ke** [comment]
You use the gradle task `genIntellijRuns` which should create two tasks, MinecraftClient and Server. Then you click Edit configurations and add it as a command line parameter.
![Screenshot 2022-04-24 231443](https://user-images.githubusercontent.com/56741599/164997044-b3f43807-a08f-48d5-8a2f-dde4db47d568.png)
Is that what you asked for?

**Comment by ThnksCJ** [comment]
Kinda because the installer adds the --tweakclass class from the lib that's the bit I need is how does it açcually inject into Minecraft from the tweakclass arg

**Comment by 3arthqu4ke** [comment]
Does it not work or is that a question? The [LaunchWrapper](https://github.com/Mojang/LegacyLauncher/blob/a4801b70f8a0148c6e6279ec2e91527e8019e1c8/src/main/java/net/minecraft/launchwrapper/Launch.java#L47) finds all classes you specify via this argument, loads and applies them. We use our Tweaker to just start Mixin and make some Hooks in Minecrafts code which makes our code run.

**Comment by ThnksCJ** [comment]
U helped alot açcually and I got a working version of what I wanted thank u lol
