### ISSUE TITLE
rechams

### ISSUE THREAD

**Issue by GentlemanMC** [3arthqu4ke/3arthh4ck#5]
they just... 
dont work

**Comment by GentlemanMC** [comment]
chams module doesnt work too

**Comment by master7720** [comment]
you gotta config rechams to work lol

**Comment by threevt** [comment]
Chams will be fixed but rechams are no longer being worked on

**Comment by 3arthqu4ke** [comment]
They will probably be removed soon, they never really worked apparently

**Comment by GentlemanMC** [comment]
kk tysm

**Comment by master7720** [comment]
> They will probably be removed soon, they never really worked apparently

hm they worked for my all i had to do is config them but there was one setting that always made you crash your game
