### ISSUE TITLE
[FEATURE] Cevbreaker

### ISSUE THREAD

**Issue by Nope0xAL4TAC** [3arthqu4ke/3arthh4ck#53]
add a cev breaker

**Comment by master7720** [comment]
This is already a module

**Comment by Nope0xAL4TAC** [comment]
> This is already a module

what? in which version?

**Comment by lyricnight** [comment]
> > This is already a module
> 
> what? in which version?

its called crystalbomber its in combat

**Comment by master7720** [comment]
i am pretty sure speedmine has a cev setting idk i havent use 3arthh4ack in a while

**Comment by master7720** [comment]
> 

its a speedmine setting in 1.3.1

**Comment by master7720** [comment]
> > This is already a module
> 
> what? in which version?

its a speedmine setting in 1.3.1
