### ISSUE TITLE
[support] how to use image chams

### ISSUE THREAD

**Issue by GentlemanMC** [3arthqu4ke/3arthh4ck#54]
lol please help me

**Comment by master7720** [comment]
bro....

**Comment by ZenovJB** [comment]
> lol please help me

sand monkey ooga booga lel u live in saudi arabia 3rd worlder quit this game

**Comment by GentlemanMC** [comment]
> > lol please help me
> 
> sand monkey ooga booga lel u live in saudi arabia 3rd worlder quit this game

no one aksed + no one cares about ur opinion + u live in russia + even russians hate u (lmfao)

**Comment by GurteX** [comment]
ratio

**Comment by threevt** [comment]
god will punish all of you

**Comment by GurteX** [comment]
> god will punish all of you

prepare
