### ISSUE TITLE
[BUG]Offhand Being Shit

### ISSUE THREAD

**Issue by MrBubblegum** [3arthqu4ke/3arthh4ck#59]
Offhand Failing sometimes at 200 ping

**Comment by MrBubblegum** [comment]
Its annoying af

**Comment by Nutelaspaceman** [comment]
> Offhand Failing sometimes at 200 ping

OMG WHAT!!!??? a bad config for offhand isn't acting perfectly fine in a fight between 10 and 200 ms??? wow thats a bug!!!! 😱😱😱

**Comment by 3arthqu4ke** [comment]
There's no way to make an Offhand work consistently at 200ms. You can try to give yourself better chances with Async-Totem and the `Fast-...` Settings in the Packets module but that's it.

**Comment by GurteX** [comment]
he totem failed on 200ms
