### ISSUE TITLE
[BUG] Viewmodel not working with future

### ISSUE THREAD

**Issue by nossravgni** [3arthqu4ke/3arthh4ck#63]
The Viewmodel module is a bit messy when playing with Future.

"OffHand-X" Doesn't do anything at all but "MainHand-X" seems to be fine.
The "Angle-Translate" is fucked and so is the "Translate" settings.

**Comment by 3arthqu4ke** [comment]
Duplicate of #24. Just use Futures Viewmodel? If theirs is missing features I might consider it.

**Comment by nossravgni** [comment]
I like 3arthh4cks more so it would be nice if it was fixed.
