### ISSUE TITLE
[BUG]Renders Fucking Itself

### ISSUE THREAD

**Issue by MrBubblegum** [3arthqu4ke/3arthh4ck#64]
sometimes my renders fuck itself like hole esp when i look away the hole esp moves to air and nametags do the same thing and they stay like this for a minute or something and then go to there normal places

**Comment by 3arthqu4ke** [comment]
Other clients? Screenshots?

**Comment by 3arthqu4ke** [comment]
And you use no other mods? Have you tried 1.6.1: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2287585314 ?

**Comment by MrBubblegum** [comment]
i use 3 other mods with earthhack but they dont affect any other client's renders
