### ISSUE TITLE
nametags module issue

### ISSUE THREAD

**Issue by Tr4p2GI1tcH** [3arthqu4ke/3arthh4ck#65]
when i turn on nametags i see that the vanilla nametags render ABOVE the custom nametags
@3arthqu4ke  fix thi

**Comment by 3arthqu4ke** [comment]
You probably use other mods which are the cause of this.

**Comment by Tr4p2GI1tcH** [comment]
> You probably use other mods which are the cause of this.

i dont, i use earth 1.6.1 alone

**Comment by 3arthqu4ke** [comment]
I need a screenshot, your Nametags config and logs. Is this happening on one specific server?

**Comment by 3arthqu4ke** [comment]
logs are more important than ss, ty

**Comment by Tr4p2GI1tcH** [comment]
thx ill send config

**Comment by Tr4p2GI1tcH** [comment]
https://www.mediafire.com/file/jdwc6ht1myk7dcl/default.json/file

**Comment by 3arthqu4ke** [comment]
Could you send the log? Did it fix itself?
