### ISSUE TITLE
[BUG] chunks flickering

### ISSUE THREAD

**Issue by GSstarGamer** [3arthqu4ke/3arthh4ck#68]
**Describe the bug**

**To Reproduce**
1. play 3arthh4ck

**Expected behavior**
Chunks are flickering, this is not an crash. If I move to an different chunk, it works only for that chunk, and others flicker
**Crashlog**
Not an crash

**Additional context**
Heres a video, steamable don't wok for me :C
https://seupload.com/shared/7j3cfqcwpwid1kdmzpo91g_ir11tb0p1xmv6yo8wp_ydxsm63ndqjhi7xywneqcyqhgrhoz732fnsnqux9chyqr1pp2i0rt7yvp-9hkrocyzz-z8knq02xqsu24pos3s

**Comment by vanyamcr2** [comment]
Same here

**Comment by 3arthqu4ke** [comment]
use 1.6.2

**Comment by GSstarGamer** [comment]
> use 1.6.2

😎
