### ISSUE TITLE
[FEATURE] Customization of offhand items

### ISSUE THREAD

**Issue by vanyamcr2** [3arthqu4ke/3arthh4ck#71]
**Is your feature request related to a problem? Please describe.**
I don't enjoy having gappels in my offhand. If you can add an option in the offhand module to disable, gapples that would be amazing.

**Describe the solution you'd like**
An option in module " Offhand" that allows you to customize items in your offhand on different occasions

Thank you!

**Comment by 3arthqu4ke** [comment]
Turn off Sword-Gapple? Saw it in your config.

**Comment by vanyamcr** [comment]
> Turn off Sword-Gapple? Saw it in your config.

Even if I don't hold sword in my hand still switches to it

**Comment by master7720** [comment]
> > Turn off Sword-Gapple? Saw it in your config.
> 
> Even if I don't hold sword in my hand still switches to it

weird

**Comment by iJese-New** [comment]
please keep in mind that this offhand is very bad, I recommend the creator to create one similar to the one in future
