### ISSUE TITLE
[BUG]earthhack making it impossible to join singleplayer worlds and more

### ISSUE THREAD

**Issue by MrBubblegum** [3arthqu4ke/3arthh4ck#74]
basically if you edit a config a lot then there is a chance the config wont let you join any singleplayer world and if you try going to a different dimension you go in the sky with no blocks and cant move or do shit and you have to rejoin the server to fix it but if you go to a another dimension the same thing happens

**Comment by Tr4p2GI1tcH** [comment]
try 1.6.2, it fixed it

**Comment by MrBubblegum** [comment]
still happens

**Comment by 3arthqu4ke** [comment]
Other mods, config, logs??
