### ISSUE TITLE
[BUG] 3arthqu4ke brain fail

### ISSUE THREAD

**Issue by GurteX** [3arthqu4ke/3arthh4ck#79]
what are you doin bro

**Comment by 3arthqu4ke** [comment]
??? wdym

**Comment by GurteX** [comment]
> ??? wdym

what are you doin here

**Comment by GurteX** [comment]
arent u dead or smthn

**Comment by 3arthqu4ke** [comment]
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
There were some things I want to fix, will probably disappear again soon

**Comment by GurteX** [comment]
> 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 There were some things I want to fix, will probably disappear again soon

ok bro go play lego 🥦🥦🥦
