### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BebSxy** [3arthqu4ke/3arthh4ck#83]
Please fix rotations

if i use silent alternative on future and 3arth surround it desync / cant place

lol, weird

**Comment by 3arthqu4ke** [comment]
where are your checkboxes, logs, screenshots etc?? pls follow the issue template

**Comment by 3arthqu4ke** [comment]
its kinda unfixable without breaking future in the process. is this with the compatibility module on?

**Comment by CascadeDemon** [comment]
> Please fix rotations
> 
> if i use silent alternative on future and 3arth surround it desync / cant place
> 
> lol, weird

user issue nigger
