### ISSUE TITLE
[FEATURE] Better Popchams

### ISSUE THREAD

**Issue by BebSxy** [3arthqu4ke/3arthh4ck#84]
Movement of arms and legs in popchams / y movement, -7.0 min. 7.0 max

**Comment by threevt** [comment]
you have days to live

**Comment by CascadeDemon** [comment]
ugly mexican nigger

**Comment by mdo992** [comment]
how did this guy get his comment deleted

**Comment by CascadeDemon** [comment]
> how did this guy get his comment deleted

nigger abuse

**Comment by cattyngmd** [comment]
https://github.com/3arthqu4ke/3arthh4ck/pull/106

**Comment by BebSxy** [comment]
based cattyn
