### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#85]
**Describe the bug**  
Tickshift doesn't work when bowspam is on
**To Reproduce**  
1. Turn on tickshift
2. Turn on bowspam
3. Tickshift wont work!

**Comment by 3arthqu4ke** [comment]
Do you use Bowspam - Bowbomb?

**Comment by Zane2b2t** [comment]
> Do you use Bowspam - Bowbomb?

no regular bowspam without rape & bowbomb

**Comment by 3arthqu4ke** [comment]
I am sorry but I cant recreate this. What do you mean with TickShift doesnt work? Does it lag you back? Is there a number behind tickshift in the arraylist? Do you use other clients? Send Screenshots of your configs!! not enough info!!!sdgasdlgasöldgjaöl

**Comment by Zane2b2t** [comment]
> I am sorry but I cant recreate this. What do you mean with TickShift doesnt work? Does it lag you back? Is there a number behind tickshift in the arraylist? Do you use other clients? Send Screenshots of your configs!! not enough info!!!sdgasdlgasöldgjaöl

it doesnt lag back but its just like if it wasn't turned on, will send ss of config later

**Comment by Zane2b2t** [comment]
> I am sorry but I cant recreate this. What do you mean with TickShift doesnt work? Does it lag you back? Is there a number behind tickshift in the arraylist? Do you use other clients? Send Screenshots of your configs!! not enough info!!!sdgasdlgasöldgjaöl

I'm too retarded lmao, that issue was on 1.6.3 its now fixed 1.7.6, however i will still use 1.6.3 dueto some stuff got removed like hold binds, Alot of settings from modules were removed mostly speedmine and stuff

**Comment by 3arthqu4ke** [comment]
`Because of bloat I decided to hide some of the more complicated Settings by default. You can find those by using the Settings module.`
