### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#86]
**Describe the bug**  
A clear and concise description of what the bug is
Double config arralylists??
**To Reproduce**  
1. Load a config ig? then load another config with diffrent names for modules (like instead of autocrstal it shows "crystal" on arraylist)
2. turn on whatever module u did that with
3. When u press the bind "crystal" will turn on on arraylist and "autocrystal" will turn off. doesnt affect anything at all its just hella confusing specialy with modules i need to know if theyre on like step and speed

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
I am not sure if I understand u correctly. First, I had a config loaded where it had its default name, then I loaded a config where AutoCrystal is renamed to Crystal. It just changed the Name in the Arraylist, everything fine.

You could also check the modules in the PB-Gui, maybe you need to rename those as well.

**Comment by Zane2b2t** [comment]
> I am not sure if I understand u correctly. First, I had a config loaded where AutoCrystal had its default name, then I loaded a config where AutoCrystal is renamed to Crystal. It just changed the Name in the Arraylist, everything fine.
> 
> You could also check the modules in the PB-Gui, maybe you need to rename those as well.

That maybe it tbh but it doesnt happen with my other configs
in notification it shows i turned on "crystal" in arraylist it shows i turned off "Autocrystal"
its weird asf will try what u told me

**Comment by Zane2b2t** [comment]
issue changed in 1.7.7 arraylist is now synced but every modules were duped and that was bcs of pb modules being turned on and showen in arraylist
its prob not bcs of update but bcs of restart but meh
