### ISSUE TITLE
CustomFont crashing after death[BUG]

### ISSUE THREAD

**Issue by crystalpvpnn** [3arthqu4ke/3arthh4ck#87]
https://streamable.com/wr6j9m
https://streamable.com/r637vl

**Comment by 3arthqu4ke** [comment]
Did you change jars in your mod folder while playing? Do you maybe have two jars in your mods folder?

**Comment by 3arthqu4ke** [comment]
Nvm wait Im stupid. Its one of your plugins. I will try to make the gui font update backwards compatible.

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2873590135 should fix it
