### ISSUE TITLE
[FEATURE] Central place to configure array list visibilities, config type "themes"

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#90]
the feature template looks more like a bug template lol
anyways, instead of chosing which modules are visible in arraylist inside every module's config with visible and hidden stuff
make a new module for arraylist (sepratate arraylist from HUD) and add settings and options for which modules are shows like in the **Notfication** module, also make PB arraylist not conflict with normal arraylist 

Another suggestion is to add a **Theme** to **Config-GUI** so ppl can get other's overall renders and hud without changing their entire config or copying visual settings 1 by 1
+config theme load ZaneCC as a command for example

**Comment by Zane2b2t** [comment]
Another thing that came into my mind, make it so when u bind a module to "0" it resets its bind

**Comment by 3arthqu4ke** [comment]
You know you can reset a bind with the Delete key?

**Comment by Zane2b2t** [comment]
> You know you can reset a bind with the Delete key?

oh

**Comment by GurteX** [comment]
iq lel

**Comment by Zane2b2t** [comment]
> You know you can reset a bind with the Delete key?

The delete key doesnt delete bind it just binds modules to it

**Comment by GurteX** [comment]
> > You know you can reset a bind with the Delete key?
> 
> The delete key doesnt delete bind it just binds modules to it

keyboard issue

**Comment by mdo992** [comment]
Zane2b2t
Zane 2b2T

**Comment by GurteX** [comment]
lolllll

**Comment by Zane2b2t** [comment]
I still need the theme thing :sob: 
switching texturepacks and then having my config not matching the color of the pack is triggering
