### ISSUE TITLE
[BUG] Discord RPC

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#95]
**Describe the bug**  
Discord RPC doesn't work 

**To Reproduce**  
1. Turn on the RPC module
2. Check the Discord status 
3. Nothing happen

**Expected behavior**  
RPC starts

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by Zane2b2t** [comment]
:scream:
