### ISSUE TITLE
[BUG] Packets module

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#96]
**Describe the bug**  
Packets module no more have separate pages

**To Reproduce**  
1. Open the Packets module

**Current behavior**
![packets bug report #96 3arthh4ck](https://user-images.githubusercontent.com/102620545/185493193-574f3ca1-28a4-4b30-a353-be41ef07955d.png)

**Expected behavior**  
![bug report #96 3arthh4ck correct view](https://user-images.githubusercontent.com/102620545/185493235-b72d06f9-5ac6-4d7d-bbbc-166d7aac98c3.png)

**Additional context**  
Maybe related to Clickgui complexity?

**Checklist**
- [ ] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by Zane2b2t** [comment]
> **Describe the bug** Packets module no more have separate pages
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open the Packets module
> 
> **Current behavior** ![packets bug report #96 3arthh4ck](https://user-images.githubusercontent.com/102620545/185493193-574f3ca1-28a4-4b30-a353-be41ef07955d.png)
> 
> **Expected behavior** ![bug report #96 3arthh4ck correct view](https://user-images.githubusercontent.com/102620545/185493235-b72d06f9-5ac6-4d7d-bbbc-166d7aac98c3.png)
> 
> **Additional context** Maybe related to Clickgui complexity?
> 
> **Checklist**
> 
> * [ ]  I know how to properly use check boxes.
> * [x]  I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
> * [x]  I followed the issue template.

Goto the **Client** catagory, goto the module "**Settings**" set it from beginner to expert

**Comment by Ai2473** [comment]
**No bro, because this is expert mode, and the 2 pages should be separated anyway, because one list of settings is dangerous**

**Comment by Zane2b2t** [comment]
> **No bro, because this is expert mode, and the 2 pages should be separated anyway, because one list of settings is dangerous**

It does have seprate pages tho?

**Comment by Ai2473** [comment]
It does in 1.6.2 and 1.3.1 (see the 2nd screenshot)
