### ISSUE TITLE
[FEATURE] New bind system

### ISSUE THREAD

**Issue by Shuttafaka** [3arthqu4ke/3arthh4ck#97]
Make a better bind system add the ability to bind two keys; for example: (LSHIFT + D) and make it possible to bind MOUSE5 and MOUSE4 i.e. the side mouse buttons
![unknown2.png](https://user-images.githubusercontent.com/74642478/185548253-392d44a6-a8a7-47f9-a1d1-acc519226d31.png)
![unknown-9.png](https://user-images.githubusercontent.com/74642478/185548271-cf24f66b-0708-4b22-81dd-1700760eb289.png)
![unknown3.png](https://user-images.githubusercontent.com/74642478/185548283-fb4cee5f-cbeb-469f-901c-03e8a529bae4.png)

**Comment by Zane2b2t** [comment]
I want this

**Comment by Zane2b2t** [comment]
i still cant bind with mouse side buttons :sob:

**Comment by xyzbtw** [comment]
> i still cant bind with mouse side buttons 😭

if it hasn't been done yet, you can use a spoofer to spoof your mouse buttons as a keyboard button you don't use much
